// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: devmgr/v1/devmgr.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Devmgr_ProductCreate_FullMethodName         = "/devmgr.v1.Devmgr/ProductCreate"
	Devmgr_ProductDelete_FullMethodName         = "/devmgr.v1.Devmgr/ProductDelete"
	Devmgr_ProductUpdate_FullMethodName         = "/devmgr.v1.Devmgr/ProductUpdate"
	Devmgr_ProductGetList_FullMethodName        = "/devmgr.v1.Devmgr/ProductGetList"
	Devmgr_DeviceCreate_FullMethodName          = "/devmgr.v1.Devmgr/DeviceCreate"
	Devmgr_DeviceTemplateGet_FullMethodName     = "/devmgr.v1.Devmgr/DeviceTemplateGet"
	Devmgr_DeviceImport_FullMethodName          = "/devmgr.v1.Devmgr/DeviceImport"
	Devmgr_DeviceDelete_FullMethodName          = "/devmgr.v1.Devmgr/DeviceDelete"
	Devmgr_DeviceUpdate_FullMethodName          = "/devmgr.v1.Devmgr/DeviceUpdate"
	Devmgr_DeviceGetList_FullMethodName         = "/devmgr.v1.Devmgr/DeviceGetList"
	Devmgr_DeviceOverview_FullMethodName        = "/devmgr.v1.Devmgr/DeviceOverview"
	Devmgr_DevActivate_FullMethodName           = "/devmgr.v1.Devmgr/DevActivate"
	Devmgr_DevAuth_FullMethodName               = "/devmgr.v1.Devmgr/DevAuth"
	Devmgr_DeviceCommandList_FullMethodName     = "/devmgr.v1.Devmgr/DeviceCommandList"
	Devmgr_DeviceCommandExecute_FullMethodName  = "/devmgr.v1.Devmgr/DeviceCommandExecute"
	Devmgr_DeviceCommandLogList_FullMethodName  = "/devmgr.v1.Devmgr/DeviceCommandLogList"
	Devmgr_PackageList_FullMethodName           = "/devmgr.v1.Devmgr/PackageList"
	Devmgr_DeviceVersionList_FullMethodName     = "/devmgr.v1.Devmgr/DeviceVersionList"
	Devmgr_PackageCreate_FullMethodName         = "/devmgr.v1.Devmgr/PackageCreate"
	Devmgr_PackageConfirm_FullMethodName        = "/devmgr.v1.Devmgr/PackageConfirm"
	Devmgr_PackageDelete_FullMethodName         = "/devmgr.v1.Devmgr/PackageDelete"
	Devmgr_UpgradeBatchList_FullMethodName      = "/devmgr.v1.Devmgr/UpgradeBatchList"
	Devmgr_UpgradeBatchCreate_FullMethodName    = "/devmgr.v1.Devmgr/UpgradeBatchCreate"
	Devmgr_UpgradeRecordList_FullMethodName     = "/devmgr.v1.Devmgr/UpgradeRecordList"
	Devmgr_UpgradeRecordOverview_FullMethodName = "/devmgr.v1.Devmgr/UpgradeRecordOverview"
	Devmgr_UpgradeRecordLog_FullMethodName      = "/devmgr.v1.Devmgr/UpgradeRecordLog"
	Devmgr_DeviceUpgradeCancel_FullMethodName   = "/devmgr.v1.Devmgr/DeviceUpgradeCancel"
	Devmgr_DeviceUpgradeRetry_FullMethodName    = "/devmgr.v1.Devmgr/DeviceUpgradeRetry"
)

// DevmgrClient is the client API for Devmgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DevmgrClient interface {
	// --- 产品配置 ---
	// 创建产品
	ProductCreate(ctx context.Context, in *ProductCreateReq, opts ...grpc.CallOption) (*ProductCreateRes, error)
	// 删除产品
	ProductDelete(ctx context.Context, in *ProductDeleteReq, opts ...grpc.CallOption) (*ProductDeleteRes, error)
	// 更新产品
	ProductUpdate(ctx context.Context, in *ProductUpdateReq, opts ...grpc.CallOption) (*ProductUpdateRes, error)
	// 获取产品列表
	ProductGetList(ctx context.Context, in *ProductGetListReq, opts ...grpc.CallOption) (*ProductGetListRes, error)
	// --- 设备配置 ---
	// 创建设备
	DeviceCreate(ctx context.Context, in *DeviceCreateReq, opts ...grpc.CallOption) (*DeviceCreateRes, error)
	// 获取设备创建模板文件
	DeviceTemplateGet(ctx context.Context, in *DeviceTemplateGetReq, opts ...grpc.CallOption) (*DeviceTemplateGetRes, error)
	// 批量创建设备
	DeviceImport(ctx context.Context, in *DeviceImportReq, opts ...grpc.CallOption) (*DeviceImportRes, error)
	// 删除设备
	DeviceDelete(ctx context.Context, in *DeviceDeleteReq, opts ...grpc.CallOption) (*DeviceDeleteRes, error)
	// 更新设备
	DeviceUpdate(ctx context.Context, in *DeviceUpdateReq, opts ...grpc.CallOption) (*DeviceUpdateRes, error)
	// 获取设备列表
	DeviceGetList(ctx context.Context, in *DeviceGetListReq, opts ...grpc.CallOption) (*DeviceGetListRes, error)
	// 设备概览
	DeviceOverview(ctx context.Context, in *DeviceOverviewReq, opts ...grpc.CallOption) (*DeviceOverviewRes, error)
	// --- 设备认证 ---
	// 设备激活
	DevActivate(ctx context.Context, in *DevActivateReq, opts ...grpc.CallOption) (*DevActivateRes, error)
	// 设备认证
	DevAuth(ctx context.Context, in *DevAuthReq, opts ...grpc.CallOption) (*DevAuthRes, error)
	// --- 设备远程调试 ---
	// 查询调试命令列表
	DeviceCommandList(ctx context.Context, in *DeviceCommandListReq, opts ...grpc.CallOption) (*DeviceCommandListRes, error)
	// 设备远程调试命令
	DeviceCommandExecute(ctx context.Context, in *DeviceCommandExecuteReq, opts ...grpc.CallOption) (*DeviceCommandExecuteRes, error)
	// 查询执行日志
	DeviceCommandLogList(ctx context.Context, in *DeviceCommandLogListReq, opts ...grpc.CallOption) (*DeviceCommandLogListRes, error)
	// --- 设备升级 ---
	// 查询升级包列表
	PackageList(ctx context.Context, in *PackageListReq, opts ...grpc.CallOption) (*PackageListRes, error)
	// 查询设备版本列表
	DeviceVersionList(ctx context.Context, in *DeviceVersionListReq, opts ...grpc.CallOption) (*DeviceVersionListRes, error)
	// 创建升级包
	PackageCreate(ctx context.Context, in *PackageCreateReq, opts ...grpc.CallOption) (*PackageCreateRes, error)
	// 确认升级包
	PackageConfirm(ctx context.Context, in *PackageConfirmReq, opts ...grpc.CallOption) (*PackageConfirmRes, error)
	// 删除升级包
	PackageDelete(ctx context.Context, in *PackageDeleteReq, opts ...grpc.CallOption) (*PackageDeleteRes, error)
	// 查询升级批次列表
	UpgradeBatchList(ctx context.Context, in *UpgradeBatchListReq, opts ...grpc.CallOption) (*UpgradeBatchListRes, error)
	// 创建升级批次
	UpgradeBatchCreate(ctx context.Context, in *UpgradeBatchCreateReq, opts ...grpc.CallOption) (*UpgradeBatchCreateRes, error)
	// 查询升级记录
	UpgradeRecordList(ctx context.Context, in *UpgradeRecordListReq, opts ...grpc.CallOption) (*UpgradeRecordIRes, error)
	// 升级记录总览
	UpgradeRecordOverview(ctx context.Context, in *UpgradeRecordOverviewReq, opts ...grpc.CallOption) (*UpgradeRecordOverviewRes, error)
	// 查询升级记录日志
	UpgradeRecordLog(ctx context.Context, in *UpgradeRecordLogReq, opts ...grpc.CallOption) (*UpgradeRecordLogRes, error)
	// 设备取消升级
	DeviceUpgradeCancel(ctx context.Context, in *DeviceUpgradeCancelReq, opts ...grpc.CallOption) (*DeviceUpgradeCancelRes, error)
	// 设备重新升级
	DeviceUpgradeRetry(ctx context.Context, in *DeviceUpgradeRetryReq, opts ...grpc.CallOption) (*DeviceUpgradeRetryRes, error)
}

type devmgrClient struct {
	cc grpc.ClientConnInterface
}

func NewDevmgrClient(cc grpc.ClientConnInterface) DevmgrClient {
	return &devmgrClient{cc}
}

func (c *devmgrClient) ProductCreate(ctx context.Context, in *ProductCreateReq, opts ...grpc.CallOption) (*ProductCreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductCreateRes)
	err := c.cc.Invoke(ctx, Devmgr_ProductCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) ProductDelete(ctx context.Context, in *ProductDeleteReq, opts ...grpc.CallOption) (*ProductDeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductDeleteRes)
	err := c.cc.Invoke(ctx, Devmgr_ProductDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) ProductUpdate(ctx context.Context, in *ProductUpdateReq, opts ...grpc.CallOption) (*ProductUpdateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductUpdateRes)
	err := c.cc.Invoke(ctx, Devmgr_ProductUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) ProductGetList(ctx context.Context, in *ProductGetListReq, opts ...grpc.CallOption) (*ProductGetListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductGetListRes)
	err := c.cc.Invoke(ctx, Devmgr_ProductGetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceCreate(ctx context.Context, in *DeviceCreateReq, opts ...grpc.CallOption) (*DeviceCreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceCreateRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceTemplateGet(ctx context.Context, in *DeviceTemplateGetReq, opts ...grpc.CallOption) (*DeviceTemplateGetRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceTemplateGetRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceTemplateGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceImport(ctx context.Context, in *DeviceImportReq, opts ...grpc.CallOption) (*DeviceImportRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceImportRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceDelete(ctx context.Context, in *DeviceDeleteReq, opts ...grpc.CallOption) (*DeviceDeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceDeleteRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceUpdate(ctx context.Context, in *DeviceUpdateReq, opts ...grpc.CallOption) (*DeviceUpdateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceUpdateRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceGetList(ctx context.Context, in *DeviceGetListReq, opts ...grpc.CallOption) (*DeviceGetListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceGetListRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceGetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceOverview(ctx context.Context, in *DeviceOverviewReq, opts ...grpc.CallOption) (*DeviceOverviewRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceOverviewRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DevActivate(ctx context.Context, in *DevActivateReq, opts ...grpc.CallOption) (*DevActivateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DevActivateRes)
	err := c.cc.Invoke(ctx, Devmgr_DevActivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DevAuth(ctx context.Context, in *DevAuthReq, opts ...grpc.CallOption) (*DevAuthRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DevAuthRes)
	err := c.cc.Invoke(ctx, Devmgr_DevAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceCommandList(ctx context.Context, in *DeviceCommandListReq, opts ...grpc.CallOption) (*DeviceCommandListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceCommandListRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceCommandList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceCommandExecute(ctx context.Context, in *DeviceCommandExecuteReq, opts ...grpc.CallOption) (*DeviceCommandExecuteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceCommandExecuteRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceCommandExecute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceCommandLogList(ctx context.Context, in *DeviceCommandLogListReq, opts ...grpc.CallOption) (*DeviceCommandLogListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceCommandLogListRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceCommandLogList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) PackageList(ctx context.Context, in *PackageListReq, opts ...grpc.CallOption) (*PackageListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageListRes)
	err := c.cc.Invoke(ctx, Devmgr_PackageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceVersionList(ctx context.Context, in *DeviceVersionListReq, opts ...grpc.CallOption) (*DeviceVersionListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceVersionListRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceVersionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) PackageCreate(ctx context.Context, in *PackageCreateReq, opts ...grpc.CallOption) (*PackageCreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageCreateRes)
	err := c.cc.Invoke(ctx, Devmgr_PackageCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) PackageConfirm(ctx context.Context, in *PackageConfirmReq, opts ...grpc.CallOption) (*PackageConfirmRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageConfirmRes)
	err := c.cc.Invoke(ctx, Devmgr_PackageConfirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) PackageDelete(ctx context.Context, in *PackageDeleteReq, opts ...grpc.CallOption) (*PackageDeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageDeleteRes)
	err := c.cc.Invoke(ctx, Devmgr_PackageDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) UpgradeBatchList(ctx context.Context, in *UpgradeBatchListReq, opts ...grpc.CallOption) (*UpgradeBatchListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeBatchListRes)
	err := c.cc.Invoke(ctx, Devmgr_UpgradeBatchList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) UpgradeBatchCreate(ctx context.Context, in *UpgradeBatchCreateReq, opts ...grpc.CallOption) (*UpgradeBatchCreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeBatchCreateRes)
	err := c.cc.Invoke(ctx, Devmgr_UpgradeBatchCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) UpgradeRecordList(ctx context.Context, in *UpgradeRecordListReq, opts ...grpc.CallOption) (*UpgradeRecordIRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeRecordIRes)
	err := c.cc.Invoke(ctx, Devmgr_UpgradeRecordList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) UpgradeRecordOverview(ctx context.Context, in *UpgradeRecordOverviewReq, opts ...grpc.CallOption) (*UpgradeRecordOverviewRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeRecordOverviewRes)
	err := c.cc.Invoke(ctx, Devmgr_UpgradeRecordOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) UpgradeRecordLog(ctx context.Context, in *UpgradeRecordLogReq, opts ...grpc.CallOption) (*UpgradeRecordLogRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeRecordLogRes)
	err := c.cc.Invoke(ctx, Devmgr_UpgradeRecordLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceUpgradeCancel(ctx context.Context, in *DeviceUpgradeCancelReq, opts ...grpc.CallOption) (*DeviceUpgradeCancelRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceUpgradeCancelRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceUpgradeCancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devmgrClient) DeviceUpgradeRetry(ctx context.Context, in *DeviceUpgradeRetryReq, opts ...grpc.CallOption) (*DeviceUpgradeRetryRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceUpgradeRetryRes)
	err := c.cc.Invoke(ctx, Devmgr_DeviceUpgradeRetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevmgrServer is the server API for Devmgr service.
// All implementations must embed UnimplementedDevmgrServer
// for forward compatibility.
type DevmgrServer interface {
	// --- 产品配置 ---
	// 创建产品
	ProductCreate(context.Context, *ProductCreateReq) (*ProductCreateRes, error)
	// 删除产品
	ProductDelete(context.Context, *ProductDeleteReq) (*ProductDeleteRes, error)
	// 更新产品
	ProductUpdate(context.Context, *ProductUpdateReq) (*ProductUpdateRes, error)
	// 获取产品列表
	ProductGetList(context.Context, *ProductGetListReq) (*ProductGetListRes, error)
	// --- 设备配置 ---
	// 创建设备
	DeviceCreate(context.Context, *DeviceCreateReq) (*DeviceCreateRes, error)
	// 获取设备创建模板文件
	DeviceTemplateGet(context.Context, *DeviceTemplateGetReq) (*DeviceTemplateGetRes, error)
	// 批量创建设备
	DeviceImport(context.Context, *DeviceImportReq) (*DeviceImportRes, error)
	// 删除设备
	DeviceDelete(context.Context, *DeviceDeleteReq) (*DeviceDeleteRes, error)
	// 更新设备
	DeviceUpdate(context.Context, *DeviceUpdateReq) (*DeviceUpdateRes, error)
	// 获取设备列表
	DeviceGetList(context.Context, *DeviceGetListReq) (*DeviceGetListRes, error)
	// 设备概览
	DeviceOverview(context.Context, *DeviceOverviewReq) (*DeviceOverviewRes, error)
	// --- 设备认证 ---
	// 设备激活
	DevActivate(context.Context, *DevActivateReq) (*DevActivateRes, error)
	// 设备认证
	DevAuth(context.Context, *DevAuthReq) (*DevAuthRes, error)
	// --- 设备远程调试 ---
	// 查询调试命令列表
	DeviceCommandList(context.Context, *DeviceCommandListReq) (*DeviceCommandListRes, error)
	// 设备远程调试命令
	DeviceCommandExecute(context.Context, *DeviceCommandExecuteReq) (*DeviceCommandExecuteRes, error)
	// 查询执行日志
	DeviceCommandLogList(context.Context, *DeviceCommandLogListReq) (*DeviceCommandLogListRes, error)
	// --- 设备升级 ---
	// 查询升级包列表
	PackageList(context.Context, *PackageListReq) (*PackageListRes, error)
	// 查询设备版本列表
	DeviceVersionList(context.Context, *DeviceVersionListReq) (*DeviceVersionListRes, error)
	// 创建升级包
	PackageCreate(context.Context, *PackageCreateReq) (*PackageCreateRes, error)
	// 确认升级包
	PackageConfirm(context.Context, *PackageConfirmReq) (*PackageConfirmRes, error)
	// 删除升级包
	PackageDelete(context.Context, *PackageDeleteReq) (*PackageDeleteRes, error)
	// 查询升级批次列表
	UpgradeBatchList(context.Context, *UpgradeBatchListReq) (*UpgradeBatchListRes, error)
	// 创建升级批次
	UpgradeBatchCreate(context.Context, *UpgradeBatchCreateReq) (*UpgradeBatchCreateRes, error)
	// 查询升级记录
	UpgradeRecordList(context.Context, *UpgradeRecordListReq) (*UpgradeRecordIRes, error)
	// 升级记录总览
	UpgradeRecordOverview(context.Context, *UpgradeRecordOverviewReq) (*UpgradeRecordOverviewRes, error)
	// 查询升级记录日志
	UpgradeRecordLog(context.Context, *UpgradeRecordLogReq) (*UpgradeRecordLogRes, error)
	// 设备取消升级
	DeviceUpgradeCancel(context.Context, *DeviceUpgradeCancelReq) (*DeviceUpgradeCancelRes, error)
	// 设备重新升级
	DeviceUpgradeRetry(context.Context, *DeviceUpgradeRetryReq) (*DeviceUpgradeRetryRes, error)
	mustEmbedUnimplementedDevmgrServer()
}

// UnimplementedDevmgrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDevmgrServer struct{}

func (UnimplementedDevmgrServer) ProductCreate(context.Context, *ProductCreateReq) (*ProductCreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProductCreate not implemented")
}
func (UnimplementedDevmgrServer) ProductDelete(context.Context, *ProductDeleteReq) (*ProductDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProductDelete not implemented")
}
func (UnimplementedDevmgrServer) ProductUpdate(context.Context, *ProductUpdateReq) (*ProductUpdateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProductUpdate not implemented")
}
func (UnimplementedDevmgrServer) ProductGetList(context.Context, *ProductGetListReq) (*ProductGetListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProductGetList not implemented")
}
func (UnimplementedDevmgrServer) DeviceCreate(context.Context, *DeviceCreateReq) (*DeviceCreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceCreate not implemented")
}
func (UnimplementedDevmgrServer) DeviceTemplateGet(context.Context, *DeviceTemplateGetReq) (*DeviceTemplateGetRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceTemplateGet not implemented")
}
func (UnimplementedDevmgrServer) DeviceImport(context.Context, *DeviceImportReq) (*DeviceImportRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceImport not implemented")
}
func (UnimplementedDevmgrServer) DeviceDelete(context.Context, *DeviceDeleteReq) (*DeviceDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceDelete not implemented")
}
func (UnimplementedDevmgrServer) DeviceUpdate(context.Context, *DeviceUpdateReq) (*DeviceUpdateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceUpdate not implemented")
}
func (UnimplementedDevmgrServer) DeviceGetList(context.Context, *DeviceGetListReq) (*DeviceGetListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceGetList not implemented")
}
func (UnimplementedDevmgrServer) DeviceOverview(context.Context, *DeviceOverviewReq) (*DeviceOverviewRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceOverview not implemented")
}
func (UnimplementedDevmgrServer) DevActivate(context.Context, *DevActivateReq) (*DevActivateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DevActivate not implemented")
}
func (UnimplementedDevmgrServer) DevAuth(context.Context, *DevAuthReq) (*DevAuthRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DevAuth not implemented")
}
func (UnimplementedDevmgrServer) DeviceCommandList(context.Context, *DeviceCommandListReq) (*DeviceCommandListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceCommandList not implemented")
}
func (UnimplementedDevmgrServer) DeviceCommandExecute(context.Context, *DeviceCommandExecuteReq) (*DeviceCommandExecuteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceCommandExecute not implemented")
}
func (UnimplementedDevmgrServer) DeviceCommandLogList(context.Context, *DeviceCommandLogListReq) (*DeviceCommandLogListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceCommandLogList not implemented")
}
func (UnimplementedDevmgrServer) PackageList(context.Context, *PackageListReq) (*PackageListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackageList not implemented")
}
func (UnimplementedDevmgrServer) DeviceVersionList(context.Context, *DeviceVersionListReq) (*DeviceVersionListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceVersionList not implemented")
}
func (UnimplementedDevmgrServer) PackageCreate(context.Context, *PackageCreateReq) (*PackageCreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackageCreate not implemented")
}
func (UnimplementedDevmgrServer) PackageConfirm(context.Context, *PackageConfirmReq) (*PackageConfirmRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackageConfirm not implemented")
}
func (UnimplementedDevmgrServer) PackageDelete(context.Context, *PackageDeleteReq) (*PackageDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackageDelete not implemented")
}
func (UnimplementedDevmgrServer) UpgradeBatchList(context.Context, *UpgradeBatchListReq) (*UpgradeBatchListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradeBatchList not implemented")
}
func (UnimplementedDevmgrServer) UpgradeBatchCreate(context.Context, *UpgradeBatchCreateReq) (*UpgradeBatchCreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradeBatchCreate not implemented")
}
func (UnimplementedDevmgrServer) UpgradeRecordList(context.Context, *UpgradeRecordListReq) (*UpgradeRecordIRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradeRecordList not implemented")
}
func (UnimplementedDevmgrServer) UpgradeRecordOverview(context.Context, *UpgradeRecordOverviewReq) (*UpgradeRecordOverviewRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradeRecordOverview not implemented")
}
func (UnimplementedDevmgrServer) UpgradeRecordLog(context.Context, *UpgradeRecordLogReq) (*UpgradeRecordLogRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradeRecordLog not implemented")
}
func (UnimplementedDevmgrServer) DeviceUpgradeCancel(context.Context, *DeviceUpgradeCancelReq) (*DeviceUpgradeCancelRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceUpgradeCancel not implemented")
}
func (UnimplementedDevmgrServer) DeviceUpgradeRetry(context.Context, *DeviceUpgradeRetryReq) (*DeviceUpgradeRetryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceUpgradeRetry not implemented")
}
func (UnimplementedDevmgrServer) mustEmbedUnimplementedDevmgrServer() {}
func (UnimplementedDevmgrServer) testEmbeddedByValue()                {}

// UnsafeDevmgrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevmgrServer will
// result in compilation errors.
type UnsafeDevmgrServer interface {
	mustEmbedUnimplementedDevmgrServer()
}

func RegisterDevmgrServer(s grpc.ServiceRegistrar, srv DevmgrServer) {
	// If the following call pancis, it indicates UnimplementedDevmgrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Devmgr_ServiceDesc, srv)
}

func _Devmgr_ProductCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).ProductCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_ProductCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).ProductCreate(ctx, req.(*ProductCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_ProductDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).ProductDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_ProductDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).ProductDelete(ctx, req.(*ProductDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_ProductUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).ProductUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_ProductUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).ProductUpdate(ctx, req.(*ProductUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_ProductGetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductGetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).ProductGetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_ProductGetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).ProductGetList(ctx, req.(*ProductGetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceCreate(ctx, req.(*DeviceCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceTemplateGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceTemplateGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceTemplateGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceTemplateGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceTemplateGet(ctx, req.(*DeviceTemplateGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceImportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceImport(ctx, req.(*DeviceImportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceDelete(ctx, req.(*DeviceDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceUpdate(ctx, req.(*DeviceUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceGetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceGetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceGetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceGetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceGetList(ctx, req.(*DeviceGetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceOverviewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceOverview(ctx, req.(*DeviceOverviewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DevActivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevActivateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DevActivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DevActivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DevActivate(ctx, req.(*DevActivateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DevAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DevAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DevAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DevAuth(ctx, req.(*DevAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceCommandList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceCommandListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceCommandList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceCommandList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceCommandList(ctx, req.(*DeviceCommandListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceCommandExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceCommandExecuteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceCommandExecute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceCommandExecute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceCommandExecute(ctx, req.(*DeviceCommandExecuteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceCommandLogList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceCommandLogListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceCommandLogList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceCommandLogList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceCommandLogList(ctx, req.(*DeviceCommandLogListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_PackageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).PackageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_PackageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).PackageList(ctx, req.(*PackageListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceVersionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceVersionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceVersionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceVersionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceVersionList(ctx, req.(*DeviceVersionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_PackageCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).PackageCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_PackageCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).PackageCreate(ctx, req.(*PackageCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_PackageConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageConfirmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).PackageConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_PackageConfirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).PackageConfirm(ctx, req.(*PackageConfirmReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_PackageDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).PackageDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_PackageDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).PackageDelete(ctx, req.(*PackageDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_UpgradeBatchList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeBatchListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).UpgradeBatchList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_UpgradeBatchList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).UpgradeBatchList(ctx, req.(*UpgradeBatchListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_UpgradeBatchCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeBatchCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).UpgradeBatchCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_UpgradeBatchCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).UpgradeBatchCreate(ctx, req.(*UpgradeBatchCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_UpgradeRecordList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeRecordListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).UpgradeRecordList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_UpgradeRecordList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).UpgradeRecordList(ctx, req.(*UpgradeRecordListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_UpgradeRecordOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeRecordOverviewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).UpgradeRecordOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_UpgradeRecordOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).UpgradeRecordOverview(ctx, req.(*UpgradeRecordOverviewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_UpgradeRecordLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeRecordLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).UpgradeRecordLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_UpgradeRecordLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).UpgradeRecordLog(ctx, req.(*UpgradeRecordLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceUpgradeCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceUpgradeCancelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceUpgradeCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceUpgradeCancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceUpgradeCancel(ctx, req.(*DeviceUpgradeCancelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devmgr_DeviceUpgradeRetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceUpgradeRetryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevmgrServer).DeviceUpgradeRetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Devmgr_DeviceUpgradeRetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevmgrServer).DeviceUpgradeRetry(ctx, req.(*DeviceUpgradeRetryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Devmgr_ServiceDesc is the grpc.ServiceDesc for Devmgr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Devmgr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devmgr.v1.Devmgr",
	HandlerType: (*DevmgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProductCreate",
			Handler:    _Devmgr_ProductCreate_Handler,
		},
		{
			MethodName: "ProductDelete",
			Handler:    _Devmgr_ProductDelete_Handler,
		},
		{
			MethodName: "ProductUpdate",
			Handler:    _Devmgr_ProductUpdate_Handler,
		},
		{
			MethodName: "ProductGetList",
			Handler:    _Devmgr_ProductGetList_Handler,
		},
		{
			MethodName: "DeviceCreate",
			Handler:    _Devmgr_DeviceCreate_Handler,
		},
		{
			MethodName: "DeviceTemplateGet",
			Handler:    _Devmgr_DeviceTemplateGet_Handler,
		},
		{
			MethodName: "DeviceImport",
			Handler:    _Devmgr_DeviceImport_Handler,
		},
		{
			MethodName: "DeviceDelete",
			Handler:    _Devmgr_DeviceDelete_Handler,
		},
		{
			MethodName: "DeviceUpdate",
			Handler:    _Devmgr_DeviceUpdate_Handler,
		},
		{
			MethodName: "DeviceGetList",
			Handler:    _Devmgr_DeviceGetList_Handler,
		},
		{
			MethodName: "DeviceOverview",
			Handler:    _Devmgr_DeviceOverview_Handler,
		},
		{
			MethodName: "DevActivate",
			Handler:    _Devmgr_DevActivate_Handler,
		},
		{
			MethodName: "DevAuth",
			Handler:    _Devmgr_DevAuth_Handler,
		},
		{
			MethodName: "DeviceCommandList",
			Handler:    _Devmgr_DeviceCommandList_Handler,
		},
		{
			MethodName: "DeviceCommandExecute",
			Handler:    _Devmgr_DeviceCommandExecute_Handler,
		},
		{
			MethodName: "DeviceCommandLogList",
			Handler:    _Devmgr_DeviceCommandLogList_Handler,
		},
		{
			MethodName: "PackageList",
			Handler:    _Devmgr_PackageList_Handler,
		},
		{
			MethodName: "DeviceVersionList",
			Handler:    _Devmgr_DeviceVersionList_Handler,
		},
		{
			MethodName: "PackageCreate",
			Handler:    _Devmgr_PackageCreate_Handler,
		},
		{
			MethodName: "PackageConfirm",
			Handler:    _Devmgr_PackageConfirm_Handler,
		},
		{
			MethodName: "PackageDelete",
			Handler:    _Devmgr_PackageDelete_Handler,
		},
		{
			MethodName: "UpgradeBatchList",
			Handler:    _Devmgr_UpgradeBatchList_Handler,
		},
		{
			MethodName: "UpgradeBatchCreate",
			Handler:    _Devmgr_UpgradeBatchCreate_Handler,
		},
		{
			MethodName: "UpgradeRecordList",
			Handler:    _Devmgr_UpgradeRecordList_Handler,
		},
		{
			MethodName: "UpgradeRecordOverview",
			Handler:    _Devmgr_UpgradeRecordOverview_Handler,
		},
		{
			MethodName: "UpgradeRecordLog",
			Handler:    _Devmgr_UpgradeRecordLog_Handler,
		},
		{
			MethodName: "DeviceUpgradeCancel",
			Handler:    _Devmgr_DeviceUpgradeCancel_Handler,
		},
		{
			MethodName: "DeviceUpgradeRetry",
			Handler:    _Devmgr_DeviceUpgradeRetry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "devmgr/v1/devmgr.proto",
}
