// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: dbres/v1/dbres.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dbres_CreateInstance_FullMethodName   = "/dbresv1.dbres/CreateInstance"
	Dbres_UpdateInstance_FullMethodName   = "/dbresv1.dbres/UpdateInstance"
	Dbres_CreateDatabase_FullMethodName   = "/dbresv1.dbres/CreateDatabase"
	Dbres_UpdateDatabase_FullMethodName   = "/dbresv1.dbres/UpdateDatabase"
	Dbres_CreateRDBSchema_FullMethodName  = "/dbresv1.dbres/CreateRDBSchema"
	Dbres_UpdateRDBSchema_FullMethodName  = "/dbresv1.dbres/UpdateRDBSchema"
	Dbres_CreateRDBTable_FullMethodName   = "/dbresv1.dbres/CreateRDBTable"
	Dbres_UpdateRDBTable_FullMethodName   = "/dbresv1.dbres/UpdateRDBTable"
	Dbres_CreateHisdbTable_FullMethodName = "/dbresv1.dbres/CreateHisdbTable"
	Dbres_UpdateHisdbTable_FullMethodName = "/dbresv1.dbres/UpdateHisdbTable"
	Dbres_Delete_FullMethodName           = "/dbresv1.dbres/Delete"
	Dbres_GetRdbResTree_FullMethodName    = "/dbresv1.dbres/GetRdbResTree"
	Dbres_GetHisdbResTree_FullMethodName  = "/dbresv1.dbres/GetHisdbResTree"
	Dbres_GetField_FullMethodName         = "/dbresv1.dbres/GetField"
	Dbres_CreateBinding_FullMethodName    = "/dbresv1.dbres/CreateBinding"
	Dbres_UpdateBinding_FullMethodName    = "/dbresv1.dbres/UpdateBinding"
	Dbres_GetAllBindings_FullMethodName   = "/dbresv1.dbres/GetAllBindings"
	Dbres_ReadData_FullMethodName         = "/dbresv1.dbres/ReadData"
)

// DbresClient is the client API for Dbres service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 数据库资源管理
type DbresClient interface {
	// 添加实例
	CreateInstance(ctx context.Context, in *CreateInstanceReq, opts ...grpc.CallOption) (*CreateInstanceRes, error)
	// 更新实例
	UpdateInstance(ctx context.Context, in *UpdateInstanceReq, opts ...grpc.CallOption) (*UpdateInstanceRes, error)
	// 创建数据库
	CreateDatabase(ctx context.Context, in *CreateDatabaseReq, opts ...grpc.CallOption) (*CreateDatabaseRes, error)
	// 更新数据库
	UpdateDatabase(ctx context.Context, in *UpdateDatabaseReq, opts ...grpc.CallOption) (*UpdateDatabaseRes, error)
	// 创建RDB模式
	CreateRDBSchema(ctx context.Context, in *CreateRDBSchemaReq, opts ...grpc.CallOption) (*CreateRDBSchemaRes, error)
	// 更新RDB模式
	UpdateRDBSchema(ctx context.Context, in *UpdateRDBSchemaReq, opts ...grpc.CallOption) (*UpdateRDBSchemaRes, error)
	// 创建RDB表
	CreateRDBTable(ctx context.Context, in *CreateRDBTableReq, opts ...grpc.CallOption) (*CreateRDBTableRes, error)
	// 更新RDB表
	UpdateRDBTable(ctx context.Context, in *UpdateRDBTableReq, opts ...grpc.CallOption) (*UpdateRDBTableRes, error)
	// 创建历史表
	CreateHisdbTable(ctx context.Context, in *CreateHisdbTableReq, opts ...grpc.CallOption) (*CreateHisdbTableRes, error)
	// 更新历史表
	UpdateHisdbTable(ctx context.Context, in *UpdateHisdbTableReq, opts ...grpc.CallOption) (*UpdateHisdbTableRes, error)
	// 删除资源
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteRes, error)
	// 获取关系库资源树结构
	GetRdbResTree(ctx context.Context, in *GetRdbResTreeReq, opts ...grpc.CallOption) (*GetRdbResTreeRes, error)
	// 获取历史库资源树结构
	GetHisdbResTree(ctx context.Context, in *GetHisdbResTreeReq, opts ...grpc.CallOption) (*GetHisdbResTreeRes, error)
	// 获取字段信息
	GetField(ctx context.Context, in *GetFieldReq, opts ...grpc.CallOption) (*GetFieldRes, error)
	// 绑定租户到表资源
	CreateBinding(ctx context.Context, in *CreateBindingReq, opts ...grpc.CallOption) (*CreateBindingRes, error)
	// 更新绑定信息
	UpdateBinding(ctx context.Context, in *UpdateBindingReq, opts ...grpc.CallOption) (*UpdateBindingRes, error)
	// 返回所有绑定信息
	GetAllBindings(ctx context.Context, in *GetAllBindingsReq, opts ...grpc.CallOption) (*GetAllBindingsRes, error)
	ReadData(ctx context.Context, in *ReadDataReq, opts ...grpc.CallOption) (*ReadDataRes, error)
}

type dbresClient struct {
	cc grpc.ClientConnInterface
}

func NewDbresClient(cc grpc.ClientConnInterface) DbresClient {
	return &dbresClient{cc}
}

func (c *dbresClient) CreateInstance(ctx context.Context, in *CreateInstanceReq, opts ...grpc.CallOption) (*CreateInstanceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceRes)
	err := c.cc.Invoke(ctx, Dbres_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) UpdateInstance(ctx context.Context, in *UpdateInstanceReq, opts ...grpc.CallOption) (*UpdateInstanceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInstanceRes)
	err := c.cc.Invoke(ctx, Dbres_UpdateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) CreateDatabase(ctx context.Context, in *CreateDatabaseReq, opts ...grpc.CallOption) (*CreateDatabaseRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDatabaseRes)
	err := c.cc.Invoke(ctx, Dbres_CreateDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) UpdateDatabase(ctx context.Context, in *UpdateDatabaseReq, opts ...grpc.CallOption) (*UpdateDatabaseRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDatabaseRes)
	err := c.cc.Invoke(ctx, Dbres_UpdateDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) CreateRDBSchema(ctx context.Context, in *CreateRDBSchemaReq, opts ...grpc.CallOption) (*CreateRDBSchemaRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRDBSchemaRes)
	err := c.cc.Invoke(ctx, Dbres_CreateRDBSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) UpdateRDBSchema(ctx context.Context, in *UpdateRDBSchemaReq, opts ...grpc.CallOption) (*UpdateRDBSchemaRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRDBSchemaRes)
	err := c.cc.Invoke(ctx, Dbres_UpdateRDBSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) CreateRDBTable(ctx context.Context, in *CreateRDBTableReq, opts ...grpc.CallOption) (*CreateRDBTableRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRDBTableRes)
	err := c.cc.Invoke(ctx, Dbres_CreateRDBTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) UpdateRDBTable(ctx context.Context, in *UpdateRDBTableReq, opts ...grpc.CallOption) (*UpdateRDBTableRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRDBTableRes)
	err := c.cc.Invoke(ctx, Dbres_UpdateRDBTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) CreateHisdbTable(ctx context.Context, in *CreateHisdbTableReq, opts ...grpc.CallOption) (*CreateHisdbTableRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHisdbTableRes)
	err := c.cc.Invoke(ctx, Dbres_CreateHisdbTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) UpdateHisdbTable(ctx context.Context, in *UpdateHisdbTableReq, opts ...grpc.CallOption) (*UpdateHisdbTableRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHisdbTableRes)
	err := c.cc.Invoke(ctx, Dbres_UpdateHisdbTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRes)
	err := c.cc.Invoke(ctx, Dbres_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) GetRdbResTree(ctx context.Context, in *GetRdbResTreeReq, opts ...grpc.CallOption) (*GetRdbResTreeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRdbResTreeRes)
	err := c.cc.Invoke(ctx, Dbres_GetRdbResTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) GetHisdbResTree(ctx context.Context, in *GetHisdbResTreeReq, opts ...grpc.CallOption) (*GetHisdbResTreeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHisdbResTreeRes)
	err := c.cc.Invoke(ctx, Dbres_GetHisdbResTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) GetField(ctx context.Context, in *GetFieldReq, opts ...grpc.CallOption) (*GetFieldRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFieldRes)
	err := c.cc.Invoke(ctx, Dbres_GetField_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) CreateBinding(ctx context.Context, in *CreateBindingReq, opts ...grpc.CallOption) (*CreateBindingRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBindingRes)
	err := c.cc.Invoke(ctx, Dbres_CreateBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) UpdateBinding(ctx context.Context, in *UpdateBindingReq, opts ...grpc.CallOption) (*UpdateBindingRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBindingRes)
	err := c.cc.Invoke(ctx, Dbres_UpdateBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) GetAllBindings(ctx context.Context, in *GetAllBindingsReq, opts ...grpc.CallOption) (*GetAllBindingsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllBindingsRes)
	err := c.cc.Invoke(ctx, Dbres_GetAllBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbresClient) ReadData(ctx context.Context, in *ReadDataReq, opts ...grpc.CallOption) (*ReadDataRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadDataRes)
	err := c.cc.Invoke(ctx, Dbres_ReadData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbresServer is the server API for Dbres service.
// All implementations must embed UnimplementedDbresServer
// for forward compatibility.
//
// 数据库资源管理
type DbresServer interface {
	// 添加实例
	CreateInstance(context.Context, *CreateInstanceReq) (*CreateInstanceRes, error)
	// 更新实例
	UpdateInstance(context.Context, *UpdateInstanceReq) (*UpdateInstanceRes, error)
	// 创建数据库
	CreateDatabase(context.Context, *CreateDatabaseReq) (*CreateDatabaseRes, error)
	// 更新数据库
	UpdateDatabase(context.Context, *UpdateDatabaseReq) (*UpdateDatabaseRes, error)
	// 创建RDB模式
	CreateRDBSchema(context.Context, *CreateRDBSchemaReq) (*CreateRDBSchemaRes, error)
	// 更新RDB模式
	UpdateRDBSchema(context.Context, *UpdateRDBSchemaReq) (*UpdateRDBSchemaRes, error)
	// 创建RDB表
	CreateRDBTable(context.Context, *CreateRDBTableReq) (*CreateRDBTableRes, error)
	// 更新RDB表
	UpdateRDBTable(context.Context, *UpdateRDBTableReq) (*UpdateRDBTableRes, error)
	// 创建历史表
	CreateHisdbTable(context.Context, *CreateHisdbTableReq) (*CreateHisdbTableRes, error)
	// 更新历史表
	UpdateHisdbTable(context.Context, *UpdateHisdbTableReq) (*UpdateHisdbTableRes, error)
	// 删除资源
	Delete(context.Context, *DeleteReq) (*DeleteRes, error)
	// 获取关系库资源树结构
	GetRdbResTree(context.Context, *GetRdbResTreeReq) (*GetRdbResTreeRes, error)
	// 获取历史库资源树结构
	GetHisdbResTree(context.Context, *GetHisdbResTreeReq) (*GetHisdbResTreeRes, error)
	// 获取字段信息
	GetField(context.Context, *GetFieldReq) (*GetFieldRes, error)
	// 绑定租户到表资源
	CreateBinding(context.Context, *CreateBindingReq) (*CreateBindingRes, error)
	// 更新绑定信息
	UpdateBinding(context.Context, *UpdateBindingReq) (*UpdateBindingRes, error)
	// 返回所有绑定信息
	GetAllBindings(context.Context, *GetAllBindingsReq) (*GetAllBindingsRes, error)
	ReadData(context.Context, *ReadDataReq) (*ReadDataRes, error)
	mustEmbedUnimplementedDbresServer()
}

// UnimplementedDbresServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDbresServer struct{}

func (UnimplementedDbresServer) CreateInstance(context.Context, *CreateInstanceReq) (*CreateInstanceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedDbresServer) UpdateInstance(context.Context, *UpdateInstanceReq) (*UpdateInstanceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInstance not implemented")
}
func (UnimplementedDbresServer) CreateDatabase(context.Context, *CreateDatabaseReq) (*CreateDatabaseRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDatabase not implemented")
}
func (UnimplementedDbresServer) UpdateDatabase(context.Context, *UpdateDatabaseReq) (*UpdateDatabaseRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDatabase not implemented")
}
func (UnimplementedDbresServer) CreateRDBSchema(context.Context, *CreateRDBSchemaReq) (*CreateRDBSchemaRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRDBSchema not implemented")
}
func (UnimplementedDbresServer) UpdateRDBSchema(context.Context, *UpdateRDBSchemaReq) (*UpdateRDBSchemaRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRDBSchema not implemented")
}
func (UnimplementedDbresServer) CreateRDBTable(context.Context, *CreateRDBTableReq) (*CreateRDBTableRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRDBTable not implemented")
}
func (UnimplementedDbresServer) UpdateRDBTable(context.Context, *UpdateRDBTableReq) (*UpdateRDBTableRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRDBTable not implemented")
}
func (UnimplementedDbresServer) CreateHisdbTable(context.Context, *CreateHisdbTableReq) (*CreateHisdbTableRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHisdbTable not implemented")
}
func (UnimplementedDbresServer) UpdateHisdbTable(context.Context, *UpdateHisdbTableReq) (*UpdateHisdbTableRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHisdbTable not implemented")
}
func (UnimplementedDbresServer) Delete(context.Context, *DeleteReq) (*DeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDbresServer) GetRdbResTree(context.Context, *GetRdbResTreeReq) (*GetRdbResTreeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRdbResTree not implemented")
}
func (UnimplementedDbresServer) GetHisdbResTree(context.Context, *GetHisdbResTreeReq) (*GetHisdbResTreeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHisdbResTree not implemented")
}
func (UnimplementedDbresServer) GetField(context.Context, *GetFieldReq) (*GetFieldRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetField not implemented")
}
func (UnimplementedDbresServer) CreateBinding(context.Context, *CreateBindingReq) (*CreateBindingRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBinding not implemented")
}
func (UnimplementedDbresServer) UpdateBinding(context.Context, *UpdateBindingReq) (*UpdateBindingRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBinding not implemented")
}
func (UnimplementedDbresServer) GetAllBindings(context.Context, *GetAllBindingsReq) (*GetAllBindingsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBindings not implemented")
}
func (UnimplementedDbresServer) ReadData(context.Context, *ReadDataReq) (*ReadDataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadData not implemented")
}
func (UnimplementedDbresServer) mustEmbedUnimplementedDbresServer() {}
func (UnimplementedDbresServer) testEmbeddedByValue()               {}

// UnsafeDbresServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbresServer will
// result in compilation errors.
type UnsafeDbresServer interface {
	mustEmbedUnimplementedDbresServer()
}

func RegisterDbresServer(s grpc.ServiceRegistrar, srv DbresServer) {
	// If the following call pancis, it indicates UnimplementedDbresServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dbres_ServiceDesc, srv)
}

func _Dbres_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).CreateInstance(ctx, req.(*CreateInstanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_UpdateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).UpdateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_UpdateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).UpdateInstance(ctx, req.(*UpdateInstanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_CreateDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatabaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).CreateDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_CreateDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).CreateDatabase(ctx, req.(*CreateDatabaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_UpdateDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDatabaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).UpdateDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_UpdateDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).UpdateDatabase(ctx, req.(*UpdateDatabaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_CreateRDBSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRDBSchemaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).CreateRDBSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_CreateRDBSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).CreateRDBSchema(ctx, req.(*CreateRDBSchemaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_UpdateRDBSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRDBSchemaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).UpdateRDBSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_UpdateRDBSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).UpdateRDBSchema(ctx, req.(*UpdateRDBSchemaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_CreateRDBTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRDBTableReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).CreateRDBTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_CreateRDBTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).CreateRDBTable(ctx, req.(*CreateRDBTableReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_UpdateRDBTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRDBTableReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).UpdateRDBTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_UpdateRDBTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).UpdateRDBTable(ctx, req.(*UpdateRDBTableReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_CreateHisdbTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHisdbTableReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).CreateHisdbTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_CreateHisdbTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).CreateHisdbTable(ctx, req.(*CreateHisdbTableReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_UpdateHisdbTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHisdbTableReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).UpdateHisdbTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_UpdateHisdbTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).UpdateHisdbTable(ctx, req.(*UpdateHisdbTableReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_GetRdbResTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRdbResTreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).GetRdbResTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_GetRdbResTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).GetRdbResTree(ctx, req.(*GetRdbResTreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_GetHisdbResTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHisdbResTreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).GetHisdbResTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_GetHisdbResTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).GetHisdbResTree(ctx, req.(*GetHisdbResTreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_GetField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFieldReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).GetField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_GetField_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).GetField(ctx, req.(*GetFieldReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_CreateBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBindingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).CreateBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_CreateBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).CreateBinding(ctx, req.(*CreateBindingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_UpdateBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBindingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).UpdateBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_UpdateBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).UpdateBinding(ctx, req.(*UpdateBindingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_GetAllBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBindingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).GetAllBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_GetAllBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).GetAllBindings(ctx, req.(*GetAllBindingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dbres_ReadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbresServer).ReadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbres_ReadData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbresServer).ReadData(ctx, req.(*ReadDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Dbres_ServiceDesc is the grpc.ServiceDesc for Dbres service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dbres_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbresv1.dbres",
	HandlerType: (*DbresServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInstance",
			Handler:    _Dbres_CreateInstance_Handler,
		},
		{
			MethodName: "UpdateInstance",
			Handler:    _Dbres_UpdateInstance_Handler,
		},
		{
			MethodName: "CreateDatabase",
			Handler:    _Dbres_CreateDatabase_Handler,
		},
		{
			MethodName: "UpdateDatabase",
			Handler:    _Dbres_UpdateDatabase_Handler,
		},
		{
			MethodName: "CreateRDBSchema",
			Handler:    _Dbres_CreateRDBSchema_Handler,
		},
		{
			MethodName: "UpdateRDBSchema",
			Handler:    _Dbres_UpdateRDBSchema_Handler,
		},
		{
			MethodName: "CreateRDBTable",
			Handler:    _Dbres_CreateRDBTable_Handler,
		},
		{
			MethodName: "UpdateRDBTable",
			Handler:    _Dbres_UpdateRDBTable_Handler,
		},
		{
			MethodName: "CreateHisdbTable",
			Handler:    _Dbres_CreateHisdbTable_Handler,
		},
		{
			MethodName: "UpdateHisdbTable",
			Handler:    _Dbres_UpdateHisdbTable_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Dbres_Delete_Handler,
		},
		{
			MethodName: "GetRdbResTree",
			Handler:    _Dbres_GetRdbResTree_Handler,
		},
		{
			MethodName: "GetHisdbResTree",
			Handler:    _Dbres_GetHisdbResTree_Handler,
		},
		{
			MethodName: "GetField",
			Handler:    _Dbres_GetField_Handler,
		},
		{
			MethodName: "CreateBinding",
			Handler:    _Dbres_CreateBinding_Handler,
		},
		{
			MethodName: "UpdateBinding",
			Handler:    _Dbres_UpdateBinding_Handler,
		},
		{
			MethodName: "GetAllBindings",
			Handler:    _Dbres_GetAllBindings_Handler,
		},
		{
			MethodName: "ReadData",
			Handler:    _Dbres_ReadData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbres/v1/dbres.proto",
}
