// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: filemgr/v1/filemgr.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresignDownloadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty" dc:"s3 bucket"`                                                                       // s3 bucket
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty" dc:"s3 key"`                                                                                // s3 key
	Expiry        int64                  `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty" dc:"expiry time in seconds"`                                                         // expiry time in seconds
	Intranet      bool                   `protobuf:"varint,4,opt,name=intranet,proto3" json:"intranet,omitempty" dc:"if unset or false, genernates a public URL, else genernates a internal URL"` // if unset or false, genernates a public URL, else genernates a internal URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignDownloadReq) Reset() {
	*x = PresignDownloadReq{}
	mi := &file_filemgr_v1_filemgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignDownloadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignDownloadReq) ProtoMessage() {}

func (x *PresignDownloadReq) ProtoReflect() protoreflect.Message {
	mi := &file_filemgr_v1_filemgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignDownloadReq.ProtoReflect.Descriptor instead.
func (*PresignDownloadReq) Descriptor() ([]byte, []int) {
	return file_filemgr_v1_filemgr_proto_rawDescGZIP(), []int{0}
}

func (x *PresignDownloadReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *PresignDownloadReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PresignDownloadReq) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *PresignDownloadReq) GetIntranet() bool {
	if x != nil {
		return x.Intranet
	}
	return false
}

type PresignUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Expiry        int64                  `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Intranet      bool                   `protobuf:"varint,4,opt,name=intranet,proto3" json:"intranet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignUploadReq) Reset() {
	*x = PresignUploadReq{}
	mi := &file_filemgr_v1_filemgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignUploadReq) ProtoMessage() {}

func (x *PresignUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_filemgr_v1_filemgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignUploadReq.ProtoReflect.Descriptor instead.
func (*PresignUploadReq) Descriptor() ([]byte, []int) {
	return file_filemgr_v1_filemgr_proto_rawDescGZIP(), []int{1}
}

func (x *PresignUploadReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *PresignUploadReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PresignUploadReq) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *PresignUploadReq) GetIntranet() bool {
	if x != nil {
		return x.Intranet
	}
	return false
}

type PresignDownloadRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty" dc:"HTTP GET presigned url for file downloading"` // HTTP GET presigned url for file downloading
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignDownloadRes) Reset() {
	*x = PresignDownloadRes{}
	mi := &file_filemgr_v1_filemgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignDownloadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignDownloadRes) ProtoMessage() {}

func (x *PresignDownloadRes) ProtoReflect() protoreflect.Message {
	mi := &file_filemgr_v1_filemgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignDownloadRes.ProtoReflect.Descriptor instead.
func (*PresignDownloadRes) Descriptor() ([]byte, []int) {
	return file_filemgr_v1_filemgr_proto_rawDescGZIP(), []int{2}
}

func (x *PresignDownloadRes) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PresignUploadRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty" dc:"HTTP POST presigned url for file uploading"`                                                                                            // HTTP POST presigned url for file uploading
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" dc:"required form-data parameters for POST upload request"` // required form-data parameters for POST upload request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignUploadRes) Reset() {
	*x = PresignUploadRes{}
	mi := &file_filemgr_v1_filemgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignUploadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignUploadRes) ProtoMessage() {}

func (x *PresignUploadRes) ProtoReflect() protoreflect.Message {
	mi := &file_filemgr_v1_filemgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignUploadRes.ProtoReflect.Descriptor instead.
func (*PresignUploadRes) Descriptor() ([]byte, []int) {
	return file_filemgr_v1_filemgr_proto_rawDescGZIP(), []int{3}
}

func (x *PresignUploadRes) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PresignUploadRes) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GetFileMetadataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetadataReq) Reset() {
	*x = GetFileMetadataReq{}
	mi := &file_filemgr_v1_filemgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataReq) ProtoMessage() {}

func (x *GetFileMetadataReq) ProtoReflect() protoreflect.Message {
	mi := &file_filemgr_v1_filemgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataReq.ProtoReflect.Descriptor instead.
func (*GetFileMetadataReq) Descriptor() ([]byte, []int) {
	return file_filemgr_v1_filemgr_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileMetadataReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetFileMetadataReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetFileMetadataRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty" dc:"file size in bytes"`                                                                                         // file size in bytes
	Etag          string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty" dc:"entity tag of the file content"`                                                                              // entity tag of the file content
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty" dc:"MIME type of the file (e.g. 'image/jpeg')"`                                  // MIME type of the file (e.g. "image/jpeg")
	LastModified  string                 `protobuf:"bytes,6,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty" dc:"last modification time in RFC3339 format (e.g.: '2024-03-15T12:34:56Z')"` // last modification time in RFC3339 format (e.g.: "2024-03-15T12:34:56Z")
	StorageClass  string                 `protobuf:"bytes,7,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty" dc:"storage tier/class (e.g. 'STANDARD', 'COLD')"`                            // storage tier/class (e.g. "STANDARD", "COLD")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetadataRes) Reset() {
	*x = GetFileMetadataRes{}
	mi := &file_filemgr_v1_filemgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataRes) ProtoMessage() {}

func (x *GetFileMetadataRes) ProtoReflect() protoreflect.Message {
	mi := &file_filemgr_v1_filemgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataRes.ProtoReflect.Descriptor instead.
func (*GetFileMetadataRes) Descriptor() ([]byte, []int) {
	return file_filemgr_v1_filemgr_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileMetadataRes) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetFileMetadataRes) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetFileMetadataRes) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetFileMetadataRes) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *GetFileMetadataRes) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetFileMetadataRes) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

func (x *GetFileMetadataRes) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

var File_filemgr_v1_filemgr_proto protoreflect.FileDescriptor

const file_filemgr_v1_filemgr_proto_rawDesc = "" +
	"\n" +
	"\x18filemgr/v1/filemgr.proto\x12\afilemgr\"r\n" +
	"\x12PresignDownloadReq\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\x03R\x06expiry\x12\x1a\n" +
	"\bintranet\x18\x04 \x01(\bR\bintranet\"p\n" +
	"\x10PresignUploadReq\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\x03R\x06expiry\x12\x1a\n" +
	"\bintranet\x18\x04 \x01(\bR\bintranet\"&\n" +
	"\x12PresignDownloadRes\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x9e\x01\n" +
	"\x10PresignUploadRes\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12=\n" +
	"\x06fields\x18\x02 \x03(\v2%.filemgr.PresignUploadRes.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x12GetFileMetadataReq\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xd3\x01\n" +
	"\x12GetFileMetadataRes\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12#\n" +
	"\rlast_modified\x18\x06 \x01(\tR\flastModified\x12#\n" +
	"\rstorage_class\x18\a \x01(\tR\fstorageClass2\x88\x02\n" +
	"\vFileService\x12X\n" +
	"\x1cGeneratePresignedDownloadURL\x12\x1b.filemgr.PresignDownloadReq\x1a\x1b.filemgr.PresignDownloadRes\x12R\n" +
	"\x1aGeneratePresignedUploadURL\x12\x19.filemgr.PresignUploadReq\x1a\x19.filemgr.PresignUploadRes\x12K\n" +
	"\x0fGetFileMetadata\x12\x1b.filemgr.GetFileMetadataReq\x1a\x1b.filemgr.GetFileMetadataResB\x1cZ\x1ashr_filemgr/api/filemgr/v1b\x06proto3"

var (
	file_filemgr_v1_filemgr_proto_rawDescOnce sync.Once
	file_filemgr_v1_filemgr_proto_rawDescData []byte
)

func file_filemgr_v1_filemgr_proto_rawDescGZIP() []byte {
	file_filemgr_v1_filemgr_proto_rawDescOnce.Do(func() {
		file_filemgr_v1_filemgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filemgr_v1_filemgr_proto_rawDesc), len(file_filemgr_v1_filemgr_proto_rawDesc)))
	})
	return file_filemgr_v1_filemgr_proto_rawDescData
}

var file_filemgr_v1_filemgr_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_filemgr_v1_filemgr_proto_goTypes = []any{
	(*PresignDownloadReq)(nil), // 0: filemgr.PresignDownloadReq
	(*PresignUploadReq)(nil),   // 1: filemgr.PresignUploadReq
	(*PresignDownloadRes)(nil), // 2: filemgr.PresignDownloadRes
	(*PresignUploadRes)(nil),   // 3: filemgr.PresignUploadRes
	(*GetFileMetadataReq)(nil), // 4: filemgr.GetFileMetadataReq
	(*GetFileMetadataRes)(nil), // 5: filemgr.GetFileMetadataRes
	nil,                        // 6: filemgr.PresignUploadRes.FieldsEntry
}
var file_filemgr_v1_filemgr_proto_depIdxs = []int32{
	6, // 0: filemgr.PresignUploadRes.fields:type_name -> filemgr.PresignUploadRes.FieldsEntry
	0, // 1: filemgr.FileService.GeneratePresignedDownloadURL:input_type -> filemgr.PresignDownloadReq
	1, // 2: filemgr.FileService.GeneratePresignedUploadURL:input_type -> filemgr.PresignUploadReq
	4, // 3: filemgr.FileService.GetFileMetadata:input_type -> filemgr.GetFileMetadataReq
	2, // 4: filemgr.FileService.GeneratePresignedDownloadURL:output_type -> filemgr.PresignDownloadRes
	3, // 5: filemgr.FileService.GeneratePresignedUploadURL:output_type -> filemgr.PresignUploadRes
	5, // 6: filemgr.FileService.GetFileMetadata:output_type -> filemgr.GetFileMetadataRes
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_filemgr_v1_filemgr_proto_init() }
func file_filemgr_v1_filemgr_proto_init() {
	if File_filemgr_v1_filemgr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filemgr_v1_filemgr_proto_rawDesc), len(file_filemgr_v1_filemgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filemgr_v1_filemgr_proto_goTypes,
		DependencyIndexes: file_filemgr_v1_filemgr_proto_depIdxs,
		MessageInfos:      file_filemgr_v1_filemgr_proto_msgTypes,
	}.Build()
	File_filemgr_v1_filemgr_proto = out.File
	file_filemgr_v1_filemgr_proto_goTypes = nil
	file_filemgr_v1_filemgr_proto_depIdxs = nil
}
