// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: filemgr/v1/filemgr.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileService_GeneratePresignedDownloadURL_FullMethodName = "/filemgr.FileService/GeneratePresignedDownloadURL"
	FileService_GeneratePresignedUploadURL_FullMethodName   = "/filemgr.FileService/GeneratePresignedUploadURL"
	FileService_GetFileMetadata_FullMethodName              = "/filemgr.FileService/GetFileMetadata"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	GeneratePresignedDownloadURL(ctx context.Context, in *PresignDownloadReq, opts ...grpc.CallOption) (*PresignDownloadRes, error)
	GeneratePresignedUploadURL(ctx context.Context, in *PresignUploadReq, opts ...grpc.CallOption) (*PresignUploadRes, error)
	GetFileMetadata(ctx context.Context, in *GetFileMetadataReq, opts ...grpc.CallOption) (*GetFileMetadataRes, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) GeneratePresignedDownloadURL(ctx context.Context, in *PresignDownloadReq, opts ...grpc.CallOption) (*PresignDownloadRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresignDownloadRes)
	err := c.cc.Invoke(ctx, FileService_GeneratePresignedDownloadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GeneratePresignedUploadURL(ctx context.Context, in *PresignUploadReq, opts ...grpc.CallOption) (*PresignUploadRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresignUploadRes)
	err := c.cc.Invoke(ctx, FileService_GeneratePresignedUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFileMetadata(ctx context.Context, in *GetFileMetadataReq, opts ...grpc.CallOption) (*GetFileMetadataRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileMetadataRes)
	err := c.cc.Invoke(ctx, FileService_GetFileMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
type FileServiceServer interface {
	GeneratePresignedDownloadURL(context.Context, *PresignDownloadReq) (*PresignDownloadRes, error)
	GeneratePresignedUploadURL(context.Context, *PresignUploadReq) (*PresignUploadRes, error)
	GetFileMetadata(context.Context, *GetFileMetadataReq) (*GetFileMetadataRes, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) GeneratePresignedDownloadURL(context.Context, *PresignDownloadReq) (*PresignDownloadRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePresignedDownloadURL not implemented")
}
func (UnimplementedFileServiceServer) GeneratePresignedUploadURL(context.Context, *PresignUploadReq) (*PresignUploadRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePresignedUploadURL not implemented")
}
func (UnimplementedFileServiceServer) GetFileMetadata(context.Context, *GetFileMetadataReq) (*GetFileMetadataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileMetadata not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_GeneratePresignedDownloadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignDownloadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GeneratePresignedDownloadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GeneratePresignedDownloadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GeneratePresignedDownloadURL(ctx, req.(*PresignDownloadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GeneratePresignedUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GeneratePresignedUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GeneratePresignedUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GeneratePresignedUploadURL(ctx, req.(*PresignUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFileMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileMetadataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFileMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFileMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFileMetadata(ctx, req.(*GetFileMetadataReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filemgr.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePresignedDownloadURL",
			Handler:    _FileService_GeneratePresignedDownloadURL_Handler,
		},
		{
			MethodName: "GeneratePresignedUploadURL",
			Handler:    _FileService_GeneratePresignedUploadURL_Handler,
		},
		{
			MethodName: "GetFileMetadata",
			Handler:    _FileService_GetFileMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "filemgr/v1/filemgr.proto",
}
