// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: seccenter/v1/seccenter.proto

package __

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Seccenter_RegisterUser_FullMethodName        = "/v1.seccenter/RegisterUser"
	Seccenter_ChangeUser_FullMethodName          = "/v1.seccenter/ChangeUser"
	Seccenter_UpdatePassword_FullMethodName      = "/v1.seccenter/UpdatePassword"
	Seccenter_ResetPassword_FullMethodName       = "/v1.seccenter/ResetPassword"
	Seccenter_DeleteUser_FullMethodName          = "/v1.seccenter/DeleteUser"
	Seccenter_GetUserList_FullMethodName         = "/v1.seccenter/GetUserList"
	Seccenter_GetUserInfo_FullMethodName         = "/v1.seccenter/GetUserInfo"
	Seccenter_SetUserLockStatus_FullMethodName   = "/v1.seccenter/SetUserLockStatus"
	Seccenter_SetUserUnlockStatus_FullMethodName = "/v1.seccenter/SetUserUnlockStatus"
	Seccenter_UpdateUserEmail_FullMethodName     = "/v1.seccenter/UpdateUserEmail"
	Seccenter_UpdateUserPhone_FullMethodName     = "/v1.seccenter/UpdateUserPhone"
	Seccenter_RefreshToken_FullMethodName        = "/v1.seccenter/RefreshToken"
	Seccenter_AddTenant_FullMethodName           = "/v1.seccenter/AddTenant"
	Seccenter_UpdateTenant_FullMethodName        = "/v1.seccenter/UpdateTenant"
	Seccenter_DeleteTenant_FullMethodName        = "/v1.seccenter/DeleteTenant"
	Seccenter_GetTenantList_FullMethodName       = "/v1.seccenter/GetTenantList"
	Seccenter_AddRole_FullMethodName             = "/v1.seccenter/AddRole"
	Seccenter_UpdateRole_FullMethodName          = "/v1.seccenter/UpdateRole"
	Seccenter_DeleteRole_FullMethodName          = "/v1.seccenter/DeleteRole"
	Seccenter_GetRoleList_FullMethodName         = "/v1.seccenter/GetRoleList"
	Seccenter_AddRoleMenu_FullMethodName         = "/v1.seccenter/AddRoleMenu"
	Seccenter_GetRoleMenu_FullMethodName         = "/v1.seccenter/GetRoleMenu"
	Seccenter_AddRoleApi_FullMethodName          = "/v1.seccenter/AddRoleApi"
	Seccenter_GetRoleApi_FullMethodName          = "/v1.seccenter/GetRoleApi"
	Seccenter_GetRoleCheckedMenu_FullMethodName  = "/v1.seccenter/GetRoleCheckedMenu"
	Seccenter_AddProvider_FullMethodName         = "/v1.seccenter/AddProvider"
	Seccenter_UpdateProvider_FullMethodName      = "/v1.seccenter/UpdateProvider"
	Seccenter_DeleteProvider_FullMethodName      = "/v1.seccenter/DeleteProvider"
	Seccenter_GetProviderList_FullMethodName     = "/v1.seccenter/GetProviderList"
	Seccenter_AddMenu_FullMethodName             = "/v1.seccenter/AddMenu"
	Seccenter_UpdateMenu_FullMethodName          = "/v1.seccenter/UpdateMenu"
	Seccenter_DeleteMenu_FullMethodName          = "/v1.seccenter/DeleteMenu"
	Seccenter_GetMenuList_FullMethodName         = "/v1.seccenter/GetMenuList"
	Seccenter_GetLoginCaptcha_FullMethodName     = "/v1.seccenter/GetLoginCaptcha"
	Seccenter_AccountLogin_FullMethodName        = "/v1.seccenter/AccountLogin"
	Seccenter_GetSmsOrEmailCode_FullMethodName   = "/v1.seccenter/GetSmsOrEmailCode"
	Seccenter_Logout_FullMethodName              = "/v1.seccenter/Logout"
	Seccenter_AddApi_FullMethodName              = "/v1.seccenter/AddApi"
	Seccenter_UpdateApi_FullMethodName           = "/v1.seccenter/UpdateApi"
	Seccenter_DeleteApi_FullMethodName           = "/v1.seccenter/DeleteApi"
	Seccenter_GetApiList_FullMethodName          = "/v1.seccenter/GetApiList"
	Seccenter_AddDepartment_FullMethodName       = "/v1.seccenter/AddDepartment"
	Seccenter_UpdateDepartment_FullMethodName    = "/v1.seccenter/UpdateDepartment"
	Seccenter_DeleteDepartment_FullMethodName    = "/v1.seccenter/DeleteDepartment"
	Seccenter_GetDepartmentList_FullMethodName   = "/v1.seccenter/GetDepartmentList"
)

// SeccenterClient is the client API for Seccenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeccenterClient interface {
	// 用户服务接口
	RegisterUser(ctx context.Context, in *RegisterUserReq, opts ...grpc.CallOption) (*RegisterUserRes, error)
	ChangeUser(ctx context.Context, in *ChangeUserReq, opts ...grpc.CallOption) (*ChangeUserRes, error)
	UpdatePassword(ctx context.Context, in *UpdatePwdReq, opts ...grpc.CallOption) (*UpdatePwdRes, error)
	ResetPassword(ctx context.Context, in *ResetPwdReq, opts ...grpc.CallOption) (*ResetPwdRes, error)
	DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserRes, error)
	GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListRes, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRes, error)
	SetUserLockStatus(ctx context.Context, in *SetUserLockStatusReq, opts ...grpc.CallOption) (*SetUserLockStatusRes, error)
	SetUserUnlockStatus(ctx context.Context, in *SetUserUnlockStatusReq, opts ...grpc.CallOption) (*SetUserUnlockStatusRes, error)
	UpdateUserEmail(ctx context.Context, in *UpdateUserEmailReq, opts ...grpc.CallOption) (*UpdateUserEmailRes, error)
	UpdateUserPhone(ctx context.Context, in *UpdateUserPhoneReq, opts ...grpc.CallOption) (*UpdateUserPhoneRes, error)
	RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenRes, error)
	// 租户服务接口
	AddTenant(ctx context.Context, in *AddTenantReq, opts ...grpc.CallOption) (*AddTenantRes, error)
	UpdateTenant(ctx context.Context, in *UpdateTenantReq, opts ...grpc.CallOption) (*UpdateTenantRes, error)
	DeleteTenant(ctx context.Context, in *DeleteTenantReq, opts ...grpc.CallOption) (*DeleteTenantRes, error)
	GetTenantList(ctx context.Context, in *GetTenantListReq, opts ...grpc.CallOption) (*GetTenantListRes, error)
	// 角色管理服务接口
	AddRole(ctx context.Context, in *AddRoleReq, opts ...grpc.CallOption) (*AddRoleRes, error)
	UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleRes, error)
	DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*DeleteRoleRes, error)
	GetRoleList(ctx context.Context, in *GetRoleListReq, opts ...grpc.CallOption) (*GetRoleListRes, error)
	AddRoleMenu(ctx context.Context, in *AddRoleMenuReq, opts ...grpc.CallOption) (*AddRoleMenuRes, error)
	GetRoleMenu(ctx context.Context, in *GetRoleMenuReq, opts ...grpc.CallOption) (*GetRoleMenuRes, error)
	AddRoleApi(ctx context.Context, in *AddRoleApiReq, opts ...grpc.CallOption) (*AddRoleApiRes, error)
	GetRoleApi(ctx context.Context, in *GetRoleApiReq, opts ...grpc.CallOption) (*GetRoleApiRes, error)
	GetRoleCheckedMenu(ctx context.Context, in *GetRoleCheckedMenuReq, opts ...grpc.CallOption) (*GetRoleCheckedMenuRes, error)
	// 认证源管理服务接口
	AddProvider(ctx context.Context, in *AddProviderReq, opts ...grpc.CallOption) (*AddProviderRes, error)
	UpdateProvider(ctx context.Context, in *UpdateProviderReq, opts ...grpc.CallOption) (*UpdateProviderRes, error)
	DeleteProvider(ctx context.Context, in *DeleteProviderReq, opts ...grpc.CallOption) (*DeleteProviderRes, error)
	GetProviderList(ctx context.Context, in *GetProviderListReq, opts ...grpc.CallOption) (*GetProviderListRes, error)
	// 菜单管理服务接口
	AddMenu(ctx context.Context, in *AddMenuReq, opts ...grpc.CallOption) (*AddMenuRes, error)
	UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*UpdateMenuRes, error)
	DeleteMenu(ctx context.Context, in *DeleteMenuReq, opts ...grpc.CallOption) (*DeleteMenuRes, error)
	GetMenuList(ctx context.Context, in *GetMenuListReq, opts ...grpc.CallOption) (*GetMenuListRes, error)
	// 认证服务接口
	GetLoginCaptcha(ctx context.Context, in *LoginCaptchaReq, opts ...grpc.CallOption) (*LoginCaptchaRes, error)
	AccountLogin(ctx context.Context, in *AccountLoginReq, opts ...grpc.CallOption) (*AccountLoginRes, error)
	GetSmsOrEmailCode(ctx context.Context, in *GetSmsOrEmailCodeReq, opts ...grpc.CallOption) (*GetSmsOrEmailCodeRes, error)
	Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutRes, error)
	// API接口管理服务
	AddApi(ctx context.Context, in *AddApiReq, opts ...grpc.CallOption) (*AddApiRes, error)
	UpdateApi(ctx context.Context, in *UpdateApiReq, opts ...grpc.CallOption) (*UpdateApiRes, error)
	DeleteApi(ctx context.Context, in *DeleteApiReq, opts ...grpc.CallOption) (*DeleteApiRes, error)
	GetApiList(ctx context.Context, in *GetApiListReq, opts ...grpc.CallOption) (*GetApiListRes, error)
	// 组织服务接口
	AddDepartment(ctx context.Context, in *AddDeptReq, opts ...grpc.CallOption) (*AddDeptRes, error)
	UpdateDepartment(ctx context.Context, in *UpdateDeptReq, opts ...grpc.CallOption) (*UpdateDeptRes, error)
	DeleteDepartment(ctx context.Context, in *DeleteDeptReq, opts ...grpc.CallOption) (*DeleteDeptRes, error)
	GetDepartmentList(ctx context.Context, in *GetDeptListReq, opts ...grpc.CallOption) (*GetDeptListRes, error)
}

type seccenterClient struct {
	cc grpc.ClientConnInterface
}

func NewSeccenterClient(cc grpc.ClientConnInterface) SeccenterClient {
	return &seccenterClient{cc}
}

func (c *seccenterClient) RegisterUser(ctx context.Context, in *RegisterUserReq, opts ...grpc.CallOption) (*RegisterUserRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterUserRes)
	err := c.cc.Invoke(ctx, Seccenter_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) ChangeUser(ctx context.Context, in *ChangeUserReq, opts ...grpc.CallOption) (*ChangeUserRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeUserRes)
	err := c.cc.Invoke(ctx, Seccenter_ChangeUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) UpdatePassword(ctx context.Context, in *UpdatePwdReq, opts ...grpc.CallOption) (*UpdatePwdRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePwdRes)
	err := c.cc.Invoke(ctx, Seccenter_UpdatePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) ResetPassword(ctx context.Context, in *ResetPwdReq, opts ...grpc.CallOption) (*ResetPwdRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetPwdRes)
	err := c.cc.Invoke(ctx, Seccenter_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserRes)
	err := c.cc.Invoke(ctx, Seccenter_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserListRes)
	err := c.cc.Invoke(ctx, Seccenter_GetUserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoRes)
	err := c.cc.Invoke(ctx, Seccenter_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) SetUserLockStatus(ctx context.Context, in *SetUserLockStatusReq, opts ...grpc.CallOption) (*SetUserLockStatusRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserLockStatusRes)
	err := c.cc.Invoke(ctx, Seccenter_SetUserLockStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) SetUserUnlockStatus(ctx context.Context, in *SetUserUnlockStatusReq, opts ...grpc.CallOption) (*SetUserUnlockStatusRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserUnlockStatusRes)
	err := c.cc.Invoke(ctx, Seccenter_SetUserUnlockStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) UpdateUserEmail(ctx context.Context, in *UpdateUserEmailReq, opts ...grpc.CallOption) (*UpdateUserEmailRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserEmailRes)
	err := c.cc.Invoke(ctx, Seccenter_UpdateUserEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) UpdateUserPhone(ctx context.Context, in *UpdateUserPhoneReq, opts ...grpc.CallOption) (*UpdateUserPhoneRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserPhoneRes)
	err := c.cc.Invoke(ctx, Seccenter_UpdateUserPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenRes)
	err := c.cc.Invoke(ctx, Seccenter_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) AddTenant(ctx context.Context, in *AddTenantReq, opts ...grpc.CallOption) (*AddTenantRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTenantRes)
	err := c.cc.Invoke(ctx, Seccenter_AddTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) UpdateTenant(ctx context.Context, in *UpdateTenantReq, opts ...grpc.CallOption) (*UpdateTenantRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTenantRes)
	err := c.cc.Invoke(ctx, Seccenter_UpdateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) DeleteTenant(ctx context.Context, in *DeleteTenantReq, opts ...grpc.CallOption) (*DeleteTenantRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTenantRes)
	err := c.cc.Invoke(ctx, Seccenter_DeleteTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetTenantList(ctx context.Context, in *GetTenantListReq, opts ...grpc.CallOption) (*GetTenantListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantListRes)
	err := c.cc.Invoke(ctx, Seccenter_GetTenantList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) AddRole(ctx context.Context, in *AddRoleReq, opts ...grpc.CallOption) (*AddRoleRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRoleRes)
	err := c.cc.Invoke(ctx, Seccenter_AddRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoleRes)
	err := c.cc.Invoke(ctx, Seccenter_UpdateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*DeleteRoleRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRoleRes)
	err := c.cc.Invoke(ctx, Seccenter_DeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetRoleList(ctx context.Context, in *GetRoleListReq, opts ...grpc.CallOption) (*GetRoleListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoleListRes)
	err := c.cc.Invoke(ctx, Seccenter_GetRoleList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) AddRoleMenu(ctx context.Context, in *AddRoleMenuReq, opts ...grpc.CallOption) (*AddRoleMenuRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRoleMenuRes)
	err := c.cc.Invoke(ctx, Seccenter_AddRoleMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetRoleMenu(ctx context.Context, in *GetRoleMenuReq, opts ...grpc.CallOption) (*GetRoleMenuRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoleMenuRes)
	err := c.cc.Invoke(ctx, Seccenter_GetRoleMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) AddRoleApi(ctx context.Context, in *AddRoleApiReq, opts ...grpc.CallOption) (*AddRoleApiRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRoleApiRes)
	err := c.cc.Invoke(ctx, Seccenter_AddRoleApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetRoleApi(ctx context.Context, in *GetRoleApiReq, opts ...grpc.CallOption) (*GetRoleApiRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoleApiRes)
	err := c.cc.Invoke(ctx, Seccenter_GetRoleApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetRoleCheckedMenu(ctx context.Context, in *GetRoleCheckedMenuReq, opts ...grpc.CallOption) (*GetRoleCheckedMenuRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoleCheckedMenuRes)
	err := c.cc.Invoke(ctx, Seccenter_GetRoleCheckedMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) AddProvider(ctx context.Context, in *AddProviderReq, opts ...grpc.CallOption) (*AddProviderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddProviderRes)
	err := c.cc.Invoke(ctx, Seccenter_AddProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) UpdateProvider(ctx context.Context, in *UpdateProviderReq, opts ...grpc.CallOption) (*UpdateProviderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProviderRes)
	err := c.cc.Invoke(ctx, Seccenter_UpdateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) DeleteProvider(ctx context.Context, in *DeleteProviderReq, opts ...grpc.CallOption) (*DeleteProviderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProviderRes)
	err := c.cc.Invoke(ctx, Seccenter_DeleteProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetProviderList(ctx context.Context, in *GetProviderListReq, opts ...grpc.CallOption) (*GetProviderListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderListRes)
	err := c.cc.Invoke(ctx, Seccenter_GetProviderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) AddMenu(ctx context.Context, in *AddMenuReq, opts ...grpc.CallOption) (*AddMenuRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMenuRes)
	err := c.cc.Invoke(ctx, Seccenter_AddMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*UpdateMenuRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMenuRes)
	err := c.cc.Invoke(ctx, Seccenter_UpdateMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) DeleteMenu(ctx context.Context, in *DeleteMenuReq, opts ...grpc.CallOption) (*DeleteMenuRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMenuRes)
	err := c.cc.Invoke(ctx, Seccenter_DeleteMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetMenuList(ctx context.Context, in *GetMenuListReq, opts ...grpc.CallOption) (*GetMenuListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMenuListRes)
	err := c.cc.Invoke(ctx, Seccenter_GetMenuList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetLoginCaptcha(ctx context.Context, in *LoginCaptchaReq, opts ...grpc.CallOption) (*LoginCaptchaRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginCaptchaRes)
	err := c.cc.Invoke(ctx, Seccenter_GetLoginCaptcha_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) AccountLogin(ctx context.Context, in *AccountLoginReq, opts ...grpc.CallOption) (*AccountLoginRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountLoginRes)
	err := c.cc.Invoke(ctx, Seccenter_AccountLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetSmsOrEmailCode(ctx context.Context, in *GetSmsOrEmailCodeReq, opts ...grpc.CallOption) (*GetSmsOrEmailCodeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSmsOrEmailCodeRes)
	err := c.cc.Invoke(ctx, Seccenter_GetSmsOrEmailCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutRes)
	err := c.cc.Invoke(ctx, Seccenter_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) AddApi(ctx context.Context, in *AddApiReq, opts ...grpc.CallOption) (*AddApiRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddApiRes)
	err := c.cc.Invoke(ctx, Seccenter_AddApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) UpdateApi(ctx context.Context, in *UpdateApiReq, opts ...grpc.CallOption) (*UpdateApiRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateApiRes)
	err := c.cc.Invoke(ctx, Seccenter_UpdateApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) DeleteApi(ctx context.Context, in *DeleteApiReq, opts ...grpc.CallOption) (*DeleteApiRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteApiRes)
	err := c.cc.Invoke(ctx, Seccenter_DeleteApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetApiList(ctx context.Context, in *GetApiListReq, opts ...grpc.CallOption) (*GetApiListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApiListRes)
	err := c.cc.Invoke(ctx, Seccenter_GetApiList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) AddDepartment(ctx context.Context, in *AddDeptReq, opts ...grpc.CallOption) (*AddDeptRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDeptRes)
	err := c.cc.Invoke(ctx, Seccenter_AddDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) UpdateDepartment(ctx context.Context, in *UpdateDeptReq, opts ...grpc.CallOption) (*UpdateDeptRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDeptRes)
	err := c.cc.Invoke(ctx, Seccenter_UpdateDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) DeleteDepartment(ctx context.Context, in *DeleteDeptReq, opts ...grpc.CallOption) (*DeleteDeptRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeptRes)
	err := c.cc.Invoke(ctx, Seccenter_DeleteDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seccenterClient) GetDepartmentList(ctx context.Context, in *GetDeptListReq, opts ...grpc.CallOption) (*GetDeptListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeptListRes)
	err := c.cc.Invoke(ctx, Seccenter_GetDepartmentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeccenterServer is the server API for Seccenter service.
// All implementations must embed UnimplementedSeccenterServer
// for forward compatibility.
type SeccenterServer interface {
	// 用户服务接口
	RegisterUser(context.Context, *RegisterUserReq) (*RegisterUserRes, error)
	ChangeUser(context.Context, *ChangeUserReq) (*ChangeUserRes, error)
	UpdatePassword(context.Context, *UpdatePwdReq) (*UpdatePwdRes, error)
	ResetPassword(context.Context, *ResetPwdReq) (*ResetPwdRes, error)
	DeleteUser(context.Context, *DeleteUserReq) (*DeleteUserRes, error)
	GetUserList(context.Context, *GetUserListReq) (*GetUserListRes, error)
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoRes, error)
	SetUserLockStatus(context.Context, *SetUserLockStatusReq) (*SetUserLockStatusRes, error)
	SetUserUnlockStatus(context.Context, *SetUserUnlockStatusReq) (*SetUserUnlockStatusRes, error)
	UpdateUserEmail(context.Context, *UpdateUserEmailReq) (*UpdateUserEmailRes, error)
	UpdateUserPhone(context.Context, *UpdateUserPhoneReq) (*UpdateUserPhoneRes, error)
	RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenRes, error)
	// 租户服务接口
	AddTenant(context.Context, *AddTenantReq) (*AddTenantRes, error)
	UpdateTenant(context.Context, *UpdateTenantReq) (*UpdateTenantRes, error)
	DeleteTenant(context.Context, *DeleteTenantReq) (*DeleteTenantRes, error)
	GetTenantList(context.Context, *GetTenantListReq) (*GetTenantListRes, error)
	// 角色管理服务接口
	AddRole(context.Context, *AddRoleReq) (*AddRoleRes, error)
	UpdateRole(context.Context, *UpdateRoleReq) (*UpdateRoleRes, error)
	DeleteRole(context.Context, *DeleteRoleReq) (*DeleteRoleRes, error)
	GetRoleList(context.Context, *GetRoleListReq) (*GetRoleListRes, error)
	AddRoleMenu(context.Context, *AddRoleMenuReq) (*AddRoleMenuRes, error)
	GetRoleMenu(context.Context, *GetRoleMenuReq) (*GetRoleMenuRes, error)
	AddRoleApi(context.Context, *AddRoleApiReq) (*AddRoleApiRes, error)
	GetRoleApi(context.Context, *GetRoleApiReq) (*GetRoleApiRes, error)
	GetRoleCheckedMenu(context.Context, *GetRoleCheckedMenuReq) (*GetRoleCheckedMenuRes, error)
	// 认证源管理服务接口
	AddProvider(context.Context, *AddProviderReq) (*AddProviderRes, error)
	UpdateProvider(context.Context, *UpdateProviderReq) (*UpdateProviderRes, error)
	DeleteProvider(context.Context, *DeleteProviderReq) (*DeleteProviderRes, error)
	GetProviderList(context.Context, *GetProviderListReq) (*GetProviderListRes, error)
	// 菜单管理服务接口
	AddMenu(context.Context, *AddMenuReq) (*AddMenuRes, error)
	UpdateMenu(context.Context, *UpdateMenuReq) (*UpdateMenuRes, error)
	DeleteMenu(context.Context, *DeleteMenuReq) (*DeleteMenuRes, error)
	GetMenuList(context.Context, *GetMenuListReq) (*GetMenuListRes, error)
	// 认证服务接口
	GetLoginCaptcha(context.Context, *LoginCaptchaReq) (*LoginCaptchaRes, error)
	AccountLogin(context.Context, *AccountLoginReq) (*AccountLoginRes, error)
	GetSmsOrEmailCode(context.Context, *GetSmsOrEmailCodeReq) (*GetSmsOrEmailCodeRes, error)
	Logout(context.Context, *LogoutReq) (*LogoutRes, error)
	// API接口管理服务
	AddApi(context.Context, *AddApiReq) (*AddApiRes, error)
	UpdateApi(context.Context, *UpdateApiReq) (*UpdateApiRes, error)
	DeleteApi(context.Context, *DeleteApiReq) (*DeleteApiRes, error)
	GetApiList(context.Context, *GetApiListReq) (*GetApiListRes, error)
	// 组织服务接口
	AddDepartment(context.Context, *AddDeptReq) (*AddDeptRes, error)
	UpdateDepartment(context.Context, *UpdateDeptReq) (*UpdateDeptRes, error)
	DeleteDepartment(context.Context, *DeleteDeptReq) (*DeleteDeptRes, error)
	GetDepartmentList(context.Context, *GetDeptListReq) (*GetDeptListRes, error)
	mustEmbedUnimplementedSeccenterServer()
}

// UnimplementedSeccenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeccenterServer struct{}

func (UnimplementedSeccenterServer) RegisterUser(context.Context, *RegisterUserReq) (*RegisterUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedSeccenterServer) ChangeUser(context.Context, *ChangeUserReq) (*ChangeUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeUser not implemented")
}
func (UnimplementedSeccenterServer) UpdatePassword(context.Context, *UpdatePwdReq) (*UpdatePwdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}
func (UnimplementedSeccenterServer) ResetPassword(context.Context, *ResetPwdReq) (*ResetPwdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedSeccenterServer) DeleteUser(context.Context, *DeleteUserReq) (*DeleteUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedSeccenterServer) GetUserList(context.Context, *GetUserListReq) (*GetUserListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserList not implemented")
}
func (UnimplementedSeccenterServer) GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedSeccenterServer) SetUserLockStatus(context.Context, *SetUserLockStatusReq) (*SetUserLockStatusRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserLockStatus not implemented")
}
func (UnimplementedSeccenterServer) SetUserUnlockStatus(context.Context, *SetUserUnlockStatusReq) (*SetUserUnlockStatusRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserUnlockStatus not implemented")
}
func (UnimplementedSeccenterServer) UpdateUserEmail(context.Context, *UpdateUserEmailReq) (*UpdateUserEmailRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserEmail not implemented")
}
func (UnimplementedSeccenterServer) UpdateUserPhone(context.Context, *UpdateUserPhoneReq) (*UpdateUserPhoneRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserPhone not implemented")
}
func (UnimplementedSeccenterServer) RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedSeccenterServer) AddTenant(context.Context, *AddTenantReq) (*AddTenantRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTenant not implemented")
}
func (UnimplementedSeccenterServer) UpdateTenant(context.Context, *UpdateTenantReq) (*UpdateTenantRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTenant not implemented")
}
func (UnimplementedSeccenterServer) DeleteTenant(context.Context, *DeleteTenantReq) (*DeleteTenantRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTenant not implemented")
}
func (UnimplementedSeccenterServer) GetTenantList(context.Context, *GetTenantListReq) (*GetTenantListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantList not implemented")
}
func (UnimplementedSeccenterServer) AddRole(context.Context, *AddRoleReq) (*AddRoleRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRole not implemented")
}
func (UnimplementedSeccenterServer) UpdateRole(context.Context, *UpdateRoleReq) (*UpdateRoleRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRole not implemented")
}
func (UnimplementedSeccenterServer) DeleteRole(context.Context, *DeleteRoleReq) (*DeleteRoleRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedSeccenterServer) GetRoleList(context.Context, *GetRoleListReq) (*GetRoleListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleList not implemented")
}
func (UnimplementedSeccenterServer) AddRoleMenu(context.Context, *AddRoleMenuReq) (*AddRoleMenuRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRoleMenu not implemented")
}
func (UnimplementedSeccenterServer) GetRoleMenu(context.Context, *GetRoleMenuReq) (*GetRoleMenuRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleMenu not implemented")
}
func (UnimplementedSeccenterServer) AddRoleApi(context.Context, *AddRoleApiReq) (*AddRoleApiRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRoleApi not implemented")
}
func (UnimplementedSeccenterServer) GetRoleApi(context.Context, *GetRoleApiReq) (*GetRoleApiRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleApi not implemented")
}
func (UnimplementedSeccenterServer) GetRoleCheckedMenu(context.Context, *GetRoleCheckedMenuReq) (*GetRoleCheckedMenuRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleCheckedMenu not implemented")
}
func (UnimplementedSeccenterServer) AddProvider(context.Context, *AddProviderReq) (*AddProviderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProvider not implemented")
}
func (UnimplementedSeccenterServer) UpdateProvider(context.Context, *UpdateProviderReq) (*UpdateProviderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProvider not implemented")
}
func (UnimplementedSeccenterServer) DeleteProvider(context.Context, *DeleteProviderReq) (*DeleteProviderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProvider not implemented")
}
func (UnimplementedSeccenterServer) GetProviderList(context.Context, *GetProviderListReq) (*GetProviderListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderList not implemented")
}
func (UnimplementedSeccenterServer) AddMenu(context.Context, *AddMenuReq) (*AddMenuRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMenu not implemented")
}
func (UnimplementedSeccenterServer) UpdateMenu(context.Context, *UpdateMenuReq) (*UpdateMenuRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMenu not implemented")
}
func (UnimplementedSeccenterServer) DeleteMenu(context.Context, *DeleteMenuReq) (*DeleteMenuRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMenu not implemented")
}
func (UnimplementedSeccenterServer) GetMenuList(context.Context, *GetMenuListReq) (*GetMenuListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMenuList not implemented")
}
func (UnimplementedSeccenterServer) GetLoginCaptcha(context.Context, *LoginCaptchaReq) (*LoginCaptchaRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoginCaptcha not implemented")
}
func (UnimplementedSeccenterServer) AccountLogin(context.Context, *AccountLoginReq) (*AccountLoginRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountLogin not implemented")
}
func (UnimplementedSeccenterServer) GetSmsOrEmailCode(context.Context, *GetSmsOrEmailCodeReq) (*GetSmsOrEmailCodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSmsOrEmailCode not implemented")
}
func (UnimplementedSeccenterServer) Logout(context.Context, *LogoutReq) (*LogoutRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedSeccenterServer) AddApi(context.Context, *AddApiReq) (*AddApiRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddApi not implemented")
}
func (UnimplementedSeccenterServer) UpdateApi(context.Context, *UpdateApiReq) (*UpdateApiRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApi not implemented")
}
func (UnimplementedSeccenterServer) DeleteApi(context.Context, *DeleteApiReq) (*DeleteApiRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApi not implemented")
}
func (UnimplementedSeccenterServer) GetApiList(context.Context, *GetApiListReq) (*GetApiListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApiList not implemented")
}
func (UnimplementedSeccenterServer) AddDepartment(context.Context, *AddDeptReq) (*AddDeptRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDepartment not implemented")
}
func (UnimplementedSeccenterServer) UpdateDepartment(context.Context, *UpdateDeptReq) (*UpdateDeptRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDepartment not implemented")
}
func (UnimplementedSeccenterServer) DeleteDepartment(context.Context, *DeleteDeptReq) (*DeleteDeptRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDepartment not implemented")
}
func (UnimplementedSeccenterServer) GetDepartmentList(context.Context, *GetDeptListReq) (*GetDeptListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartmentList not implemented")
}
func (UnimplementedSeccenterServer) mustEmbedUnimplementedSeccenterServer() {}
func (UnimplementedSeccenterServer) testEmbeddedByValue()                   {}

// UnsafeSeccenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeccenterServer will
// result in compilation errors.
type UnsafeSeccenterServer interface {
	mustEmbedUnimplementedSeccenterServer()
}

func RegisterSeccenterServer(s grpc.ServiceRegistrar, srv SeccenterServer) {
	// If the following call pancis, it indicates UnimplementedSeccenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Seccenter_ServiceDesc, srv)
}

func _Seccenter_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).RegisterUser(ctx, req.(*RegisterUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_ChangeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).ChangeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_ChangeUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).ChangeUser(ctx, req.(*ChangeUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePwdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_UpdatePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).UpdatePassword(ctx, req.(*UpdatePwdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPwdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).ResetPassword(ctx, req.(*ResetPwdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).DeleteUser(ctx, req.(*DeleteUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetUserList(ctx, req.(*GetUserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_SetUserLockStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserLockStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).SetUserLockStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_SetUserLockStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).SetUserLockStatus(ctx, req.(*SetUserLockStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_SetUserUnlockStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserUnlockStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).SetUserUnlockStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_SetUserUnlockStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).SetUserUnlockStatus(ctx, req.(*SetUserUnlockStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_UpdateUserEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).UpdateUserEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_UpdateUserEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).UpdateUserEmail(ctx, req.(*UpdateUserEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_UpdateUserPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPhoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).UpdateUserPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_UpdateUserPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).UpdateUserPhone(ctx, req.(*UpdateUserPhoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).RefreshToken(ctx, req.(*RefreshTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_AddTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTenantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).AddTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_AddTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).AddTenant(ctx, req.(*AddTenantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_UpdateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).UpdateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_UpdateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).UpdateTenant(ctx, req.(*UpdateTenantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_DeleteTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).DeleteTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_DeleteTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).DeleteTenant(ctx, req.(*DeleteTenantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetTenantList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetTenantList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetTenantList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetTenantList(ctx, req.(*GetTenantListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_AddRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).AddRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_AddRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).AddRole(ctx, req.(*AddRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_UpdateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).UpdateRole(ctx, req.(*UpdateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).DeleteRole(ctx, req.(*DeleteRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetRoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetRoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetRoleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetRoleList(ctx, req.(*GetRoleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_AddRoleMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoleMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).AddRoleMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_AddRoleMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).AddRoleMenu(ctx, req.(*AddRoleMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetRoleMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetRoleMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetRoleMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetRoleMenu(ctx, req.(*GetRoleMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_AddRoleApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoleApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).AddRoleApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_AddRoleApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).AddRoleApi(ctx, req.(*AddRoleApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetRoleApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetRoleApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetRoleApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetRoleApi(ctx, req.(*GetRoleApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetRoleCheckedMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleCheckedMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetRoleCheckedMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetRoleCheckedMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetRoleCheckedMenu(ctx, req.(*GetRoleCheckedMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_AddProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProviderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).AddProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_AddProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).AddProvider(ctx, req.(*AddProviderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_UpdateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProviderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).UpdateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_UpdateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).UpdateProvider(ctx, req.(*UpdateProviderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_DeleteProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProviderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).DeleteProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_DeleteProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).DeleteProvider(ctx, req.(*DeleteProviderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetProviderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetProviderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetProviderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetProviderList(ctx, req.(*GetProviderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_AddMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).AddMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_AddMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).AddMenu(ctx, req.(*AddMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_UpdateMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).UpdateMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_UpdateMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).UpdateMenu(ctx, req.(*UpdateMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_DeleteMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).DeleteMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_DeleteMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).DeleteMenu(ctx, req.(*DeleteMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetMenuList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetMenuList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetMenuList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetMenuList(ctx, req.(*GetMenuListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetLoginCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginCaptchaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetLoginCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetLoginCaptcha_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetLoginCaptcha(ctx, req.(*LoginCaptchaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_AccountLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).AccountLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_AccountLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).AccountLogin(ctx, req.(*AccountLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetSmsOrEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSmsOrEmailCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetSmsOrEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetSmsOrEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetSmsOrEmailCode(ctx, req.(*GetSmsOrEmailCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).Logout(ctx, req.(*LogoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_AddApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).AddApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_AddApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).AddApi(ctx, req.(*AddApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_UpdateApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).UpdateApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_UpdateApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).UpdateApi(ctx, req.(*UpdateApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_DeleteApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).DeleteApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_DeleteApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).DeleteApi(ctx, req.(*DeleteApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetApiList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApiListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetApiList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetApiList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetApiList(ctx, req.(*GetApiListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_AddDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).AddDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_AddDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).AddDepartment(ctx, req.(*AddDeptReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_UpdateDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).UpdateDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_UpdateDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).UpdateDepartment(ctx, req.(*UpdateDeptReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_DeleteDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).DeleteDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_DeleteDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).DeleteDepartment(ctx, req.(*DeleteDeptReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seccenter_GetDepartmentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeptListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeccenterServer).GetDepartmentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seccenter_GetDepartmentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeccenterServer).GetDepartmentList(ctx, req.(*GetDeptListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Seccenter_ServiceDesc is the grpc.ServiceDesc for Seccenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Seccenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.seccenter",
	HandlerType: (*SeccenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _Seccenter_RegisterUser_Handler,
		},
		{
			MethodName: "ChangeUser",
			Handler:    _Seccenter_ChangeUser_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _Seccenter_UpdatePassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _Seccenter_ResetPassword_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Seccenter_DeleteUser_Handler,
		},
		{
			MethodName: "GetUserList",
			Handler:    _Seccenter_GetUserList_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Seccenter_GetUserInfo_Handler,
		},
		{
			MethodName: "SetUserLockStatus",
			Handler:    _Seccenter_SetUserLockStatus_Handler,
		},
		{
			MethodName: "SetUserUnlockStatus",
			Handler:    _Seccenter_SetUserUnlockStatus_Handler,
		},
		{
			MethodName: "UpdateUserEmail",
			Handler:    _Seccenter_UpdateUserEmail_Handler,
		},
		{
			MethodName: "UpdateUserPhone",
			Handler:    _Seccenter_UpdateUserPhone_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _Seccenter_RefreshToken_Handler,
		},
		{
			MethodName: "AddTenant",
			Handler:    _Seccenter_AddTenant_Handler,
		},
		{
			MethodName: "UpdateTenant",
			Handler:    _Seccenter_UpdateTenant_Handler,
		},
		{
			MethodName: "DeleteTenant",
			Handler:    _Seccenter_DeleteTenant_Handler,
		},
		{
			MethodName: "GetTenantList",
			Handler:    _Seccenter_GetTenantList_Handler,
		},
		{
			MethodName: "AddRole",
			Handler:    _Seccenter_AddRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _Seccenter_UpdateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _Seccenter_DeleteRole_Handler,
		},
		{
			MethodName: "GetRoleList",
			Handler:    _Seccenter_GetRoleList_Handler,
		},
		{
			MethodName: "AddRoleMenu",
			Handler:    _Seccenter_AddRoleMenu_Handler,
		},
		{
			MethodName: "GetRoleMenu",
			Handler:    _Seccenter_GetRoleMenu_Handler,
		},
		{
			MethodName: "AddRoleApi",
			Handler:    _Seccenter_AddRoleApi_Handler,
		},
		{
			MethodName: "GetRoleApi",
			Handler:    _Seccenter_GetRoleApi_Handler,
		},
		{
			MethodName: "GetRoleCheckedMenu",
			Handler:    _Seccenter_GetRoleCheckedMenu_Handler,
		},
		{
			MethodName: "AddProvider",
			Handler:    _Seccenter_AddProvider_Handler,
		},
		{
			MethodName: "UpdateProvider",
			Handler:    _Seccenter_UpdateProvider_Handler,
		},
		{
			MethodName: "DeleteProvider",
			Handler:    _Seccenter_DeleteProvider_Handler,
		},
		{
			MethodName: "GetProviderList",
			Handler:    _Seccenter_GetProviderList_Handler,
		},
		{
			MethodName: "AddMenu",
			Handler:    _Seccenter_AddMenu_Handler,
		},
		{
			MethodName: "UpdateMenu",
			Handler:    _Seccenter_UpdateMenu_Handler,
		},
		{
			MethodName: "DeleteMenu",
			Handler:    _Seccenter_DeleteMenu_Handler,
		},
		{
			MethodName: "GetMenuList",
			Handler:    _Seccenter_GetMenuList_Handler,
		},
		{
			MethodName: "GetLoginCaptcha",
			Handler:    _Seccenter_GetLoginCaptcha_Handler,
		},
		{
			MethodName: "AccountLogin",
			Handler:    _Seccenter_AccountLogin_Handler,
		},
		{
			MethodName: "GetSmsOrEmailCode",
			Handler:    _Seccenter_GetSmsOrEmailCode_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Seccenter_Logout_Handler,
		},
		{
			MethodName: "AddApi",
			Handler:    _Seccenter_AddApi_Handler,
		},
		{
			MethodName: "UpdateApi",
			Handler:    _Seccenter_UpdateApi_Handler,
		},
		{
			MethodName: "DeleteApi",
			Handler:    _Seccenter_DeleteApi_Handler,
		},
		{
			MethodName: "GetApiList",
			Handler:    _Seccenter_GetApiList_Handler,
		},
		{
			MethodName: "AddDepartment",
			Handler:    _Seccenter_AddDepartment_Handler,
		},
		{
			MethodName: "UpdateDepartment",
			Handler:    _Seccenter_UpdateDepartment_Handler,
		},
		{
			MethodName: "DeleteDepartment",
			Handler:    _Seccenter_DeleteDepartment_Handler,
		},
		{
			MethodName: "GetDepartmentList",
			Handler:    _Seccenter_GetDepartmentList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seccenter/v1/seccenter.proto",
}
