// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devmgr/internal/dao/internal"
)

// commandConfigDao is the data access object for the table command_config.
// You can define custom methods on it to extend its functionality as needed.
type commandConfigDao struct {
	*internal.CommandConfigDao
}

var (
	// CommandConfig is a globally accessible object for table command_config operations.
	CommandConfig = commandConfigDao{internal.NewCommandConfigDao()}
)

// Add your custom methods and functionality below.
