// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devmgr/internal/dao/internal"
)

// commandLogDao is the data access object for the table command_log.
// You can define custom methods on it to extend its functionality as needed.
type commandLogDao struct {
	*internal.CommandLogDao
}

var (
	// CommandLog is a globally accessible object for table command_log operations.
	CommandLog = commandLogDao{internal.NewCommandLogDao()}
)

// Add your custom methods and functionality below.
