// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devmgr/internal/dao/internal"
)

// commandRecordDao is the data access object for the table command_record.
// You can define custom methods on it to extend its functionality as needed.
type commandRecordDao struct {
	*internal.CommandRecordDao
}

var (
	// CommandRecord is a globally accessible object for table command_record operations.
	CommandRecord = commandRecordDao{internal.NewCommandRecordDao()}
)

// Add your custom methods and functionality below.
