// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devmgr/internal/dao/internal"
)

// commandPermissionDao is the data access object for the table command_permission.
// You can define custom methods on it to extend its functionality as needed.
type commandPermissionDao struct {
	*internal.CommandPermissionDao
}

var (
	// CommandPermission is a globally accessible object for table command_permission operations.
	CommandPermission = commandPermissionDao{internal.NewCommandPermissionDao()}
)

// Add your custom methods and functionality below.
