// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devmgr/internal/dao/internal"
)

// taskStatusDao is the data access object for the table task_status.
// You can define custom methods on it to extend its functionality as needed.
type taskStatusDao struct {
	*internal.TaskStatusDao
}

var (
	// TaskStatus is a globally accessible object for table task_status operations.
	TaskStatus = taskStatusDao{internal.NewTaskStatusDao()}
)

// Add your custom methods and functionality below.
