// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devmgr/internal/dao/internal"
)

// upgradeLogDao is the data access object for the table upgrade_log.
// You can define custom methods on it to extend its functionality as needed.
type upgradeLogDao struct {
	*internal.UpgradeLogDao
}

var (
	// UpgradeLog is a globally accessible object for table upgrade_log operations.
	UpgradeLog = upgradeLogDao{internal.NewUpgradeLogDao()}
)

// Add your custom methods and functionality below.
