// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devmgr/internal/dao/internal"
)

// upgradeBatchDao is the data access object for the table upgrade_batch.
// You can define custom methods on it to extend its functionality as needed.
type upgradeBatchDao struct {
	*internal.UpgradeBatchDao
}

var (
	// UpgradeBatch is a globally accessible object for table upgrade_batch operations.
	UpgradeBatch = upgradeBatchDao{internal.NewUpgradeBatchDao()}
)

// Add your custom methods and functionality below.
