// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devmgr/internal/dao/internal"
)

// upgradeRecordDao is the data access object for the table upgrade_record.
// You can define custom methods on it to extend its functionality as needed.
type upgradeRecordDao struct {
	*internal.UpgradeRecordDao
}

var (
	// UpgradeRecord is a globally accessible object for table upgrade_record operations.
	UpgradeRecord = upgradeRecordDao{internal.NewUpgradeRecordDao()}
)

// Add your custom methods and functionality below.
