// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devmgr/internal/dao/internal"
)

// upgradePackageDao is the data access object for the table upgrade_package.
// You can define custom methods on it to extend its functionality as needed.
type upgradePackageDao struct {
	*internal.UpgradePackageDao
}

var (
	// UpgradePackage is a globally accessible object for table upgrade_package operations.
	UpgradePackage = upgradePackageDao{internal.NewUpgradePackageDao()}
)

// Add your custom methods and functionality below.
