// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devmgr/internal/dao/internal"
)

// upgradeMessageDao is the data access object for the table upgrade_message.
// You can define custom methods on it to extend its functionality as needed.
type upgradeMessageDao struct {
	*internal.UpgradeMessageDao
}

var (
	// UpgradeMessage is a globally accessible object for table upgrade_message operations.
	UpgradeMessage = upgradeMessageDao{internal.NewUpgradeMessageDao()}
)

// Add your custom methods and functionality below.
