// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package devmgr_http

import (
	"devmgr/api/devmgr_http"
)

type ControllerV1 struct{}

func NewV1() devmgr_http.IDevmgrHttpV1 {
	return &ControllerV1{}
}
